#include <stdio.h>
#include <dos.h>
#include <conio.h>
#include <string.h>
#include <stdlib.h>
#include "gamelogic.h"

GameVerb *firstverb = NULL;
GameString *GameStrings = NULL;

GameAction ACTIONS_MENU[] = {

    {VERB_ONENTRY, ACTION_SCREENLINES, 80},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_MENU},
    {VERB_ONENTRY, ACTION_DRAWMENU, 0},
    {VERB_PLAY, ACTION_GOTOSTATE, STATE_STANDING},
    {VERB_PLAY, ACTION_TEXTOUTPUT, STRING_REALLYNEEDSHIT},
    {VERB_DELETE, ACTION_DELETEAWARDS, 0},
    {VERB_DELETE, ACTION_GOTOSTATE, STATE_STANDING},
    {VERB_AWARDS, ACTION_GOTOSTATE, STATE_AWARDS},
    {VERB_MENU, ACTION_TEXTOUTPUT, STRING_ALREADYMENU},
    {VERB_QUIT, ACTION_EXITGAME, 0},
    {VERB_IDIOT, ACTION_TEXTOUTPUT, STRING_IDIOT},
    {VERB_CREDITS, ACTION_GOTOSTATE, STATE_CREDITS},
    {VERB_SHIT, ACTION_GOTOSTATE, STATE_STARTINGGUN},
    {0,0,0}
};

GameAction ACTIONS_STANDING[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 344},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_STANDING},
    {VERB_SHIT, ACTION_GOTOSTATE, STATE_SHITPANTSSTANDING},
    {VERB_SHITPANTS, ACTION_GOTOSTATE, STATE_FARTPANTSON},
    {VERB_FART, ACTION_GOTOSTATE, STATE_FARTPANTSON},
    {VERB_SHITTOILET, ACTION_TEXTOUTPUT, STRING_WHATTOILET},
    {VERB_DONTSHIT, ACTION_GOTOSTATE, STATE_DONTSHITPANTSON},
    {VERB_BREAK, ACTION_GOTOSTATE, STATE_BREAKPANTSON},
    {VERB_DIE, ACTION_GOTOSTATE, STATE_DIEPANTSON},
    {VERB_REMOVEPANTS, ACTION_GOTOSTATE, STATE_STANDINGPANTSOFF},
    {VERB_REMOVEPANTS, ACTION_TEXTOUTPUT, STRING_REMOVEPANTS},
    {VERB_WEARPANTS, ACTION_TEXTOUTPUT, STRING_ALREADYON },
    {VERB_OPENDOOR, ACTION_TEXTOUTPUT, STRING_PUSHDOOR},
    {VERB_PULLDOOR, ACTION_GOTOSTATE, STATE_DOOROPEN},
    {VERB_PULLDOOR, ACTION_TEXTOUTPUT, STRING_PULLDOOR},
    {VERB_CLOSEDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYCLOSED},
    {VERB_SITTOILET, ACTION_TEXTOUTPUT, STRING_CANTSIT},
    {VERB_STAND, ACTION_TEXTOUTPUT, STRING_STANDMORE},
    {VERB_LOOK, ACTION_TEXTOUTPUT, STRING_LOOK},
    {VERB_LOOKWASHROOM, ACTION_TEXTOUTPUT, STRING_CANTSEE},
    {VERB_LOOKDOOR, ACTION_TEXTOUTPUT, STRING_LOOKDOOR},
    {VERB_LOOKTOILET, ACTION_TEXTOUTPUT, STRING_WHATTOILET},
    {VERB_TIMEOUT, ACTION_GOTOSTATE, STATE_TIMEOVERSTANDINGPANTSON },
    {VERB_PILLSACTIVE, ACTION_GOTOSTATE, STATE_PILLSSTANDINGPANTSON1},
    {0,0,0}
};

GameAction ACTIONS_STANDINGPANTSOFF[] = {
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_STANDINGPANTSOFF},
    {VERB_SHIT, ACTION_GOTOSTATE, STATE_SHITONFLOOR},
    {VERB_SHITPANTS, ACTION_GOTOSTATE, STATE_SHITINPANTSWHILEOFF},
    {VERB_FART, ACTION_GOTOSTATE, STATE_FARTPANTSOFF},
    {VERB_SHITTOILET, ACTION_TEXTOUTPUT, STRING_WHATTOILET},
    {VERB_DONTSHIT, ACTION_GOTOSTATE, STATE_DONTSHITPANTSOFF},
    {VERB_BREAK, ACTION_GOTOSTATE, STATE_BREAKPANTSOFF},
    {VERB_DIE, ACTION_GOTOSTATE, STATE_DIEPANTSOFF},
    {VERB_REMOVEPANTS, ACTION_TEXTOUTPUT, STRING_ALREADYOFF},
    {VERB_WEARPANTS, ACTION_GOTOSTATE, STATE_STANDING},
    {VERB_WEARPANTS, ACTION_TEXTOUTPUT, STRING_WEARPANTS },
    {VERB_OPENDOOR, ACTION_TEXTOUTPUT, STRING_PUSHDOOR},
    {VERB_PULLDOOR, ACTION_GOTOSTATE, STATE_DOOROPENPANTSOFF},
    {VERB_PULLDOOR, ACTION_TEXTOUTPUT, STRING_PULLDOOR},
    {VERB_CLOSEDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYCLOSED},
    {VERB_SITTOILET, ACTION_TEXTOUTPUT, STRING_CANTSIT},
    {VERB_STAND, ACTION_TEXTOUTPUT, STRING_STANDMORE},
    {VERB_LOOK, ACTION_TEXTOUTPUT, STRING_LOOKNOPANTS},
    {VERB_LOOKWASHROOM, ACTION_TEXTOUTPUT, STRING_CANTSEE},
    {VERB_LOOKDOOR, ACTION_TEXTOUTPUT, STRING_LOOKDOOR},
    {VERB_LOOKTOILET, ACTION_TEXTOUTPUT, STRING_WHATTOILET},
    {VERB_TIMEOUT, ACTION_GOTOSTATE, STATE_TIMEOVERSTANDINGPANTSOFF },
    {VERB_PILLSACTIVE, ACTION_GOTOSTATE, STATE_PILLSSTANDINGPANTSOFF1},
    {0,0,0}
};

GameAction ACTIONS_DOOROPEN[] = {
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_DOOROPEN},
    {VERB_SHIT, ACTION_GOTOSTATE, STATE_SHITPANTSSTANDING},
    {VERB_SHITPANTS, ACTION_GOTOSTATE, STATE_FARTPANTSON},
    {VERB_FART, ACTION_GOTOSTATE, STATE_FARTPANTSON},
    {VERB_SHITTOILET, ACTION_GOTOSTATE, STATE_SHITINPANTSSITTING},
    {VERB_DONTSHIT, ACTION_GOTOSTATE, STATE_DONTSHITPANTSON},
    {VERB_BREAK, ACTION_GOTOSTATE, STATE_BREAKPANTSON},
    {VERB_DIE, ACTION_GOTOSTATE, STATE_DIEPANTSON},
    {VERB_REMOVEPANTS, ACTION_GOTOSTATE, STATE_DOOROPENPANTSOFF},
    {VERB_REMOVEPANTS, ACTION_TEXTOUTPUT, STRING_REMOVEPANTS},
    {VERB_WEARPANTS, ACTION_TEXTOUTPUT, STRING_ALREADYON },
    {VERB_OPENDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_PULLDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_CLOSEDOOR, ACTION_GOTOSTATE, STATE_STANDING},
    {VERB_CLOSEDOOR, ACTION_TEXTOUTPUT, STRING_CLOSEDOOR},
    {VERB_SITTOILET, ACTION_GOTOSTATE, STATE_ONTOILET},
    {VERB_SITTOILET, ACTION_TEXTOUTPUT, STRING_SITONTOILET},
    {VERB_STAND, ACTION_TEXTOUTPUT, STRING_STANDMORE},
    {VERB_LOOK, ACTION_TEXTOUTPUT, STRING_LOOKDOOROPEN},
    {VERB_LOOKWASHROOM, ACTION_TEXTOUTPUT, STRING_LOOKWASHROOM},
    {VERB_LOOKDOOR, ACTION_TEXTOUTPUT, STRING_LOOKDOOR},
    {VERB_LOOKTOILET, ACTION_TEXTOUTPUT, STRING_LOOKTOILET},
    {VERB_TIMEOUT, ACTION_GOTOSTATE, STATE_TIMEOVERSTANDINGPANTSON },
    {VERB_PILLSACTIVE, ACTION_GOTOSTATE, STATE_PILLSSTANDINGPANTSON1},
    {0,0,0}
};

GameAction ACTIONS_DOOROPENPANTSOFF[] = {
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_DOOROPENPANTSOFF},
    {VERB_SHIT, ACTION_GOTOSTATE, STATE_SHITONFLOOR},
    {VERB_SHITPANTS, ACTION_GOTOSTATE, STATE_SHITINPANTSWHILEOFF},
    {VERB_FART, ACTION_GOTOSTATE, STATE_FARTPANTSOFF},
    {VERB_SHITTOILET, ACTION_GOTOSTATE, STATE_SHITINTOILET},
    {VERB_DONTSHIT, ACTION_GOTOSTATE, STATE_DONTSHITPANTSOFF},
    {VERB_BREAK, ACTION_GOTOSTATE, STATE_BREAKPANTSOFF},
    {VERB_DIE, ACTION_GOTOSTATE, STATE_DIEPANTSOFF},
    {VERB_REMOVEPANTS, ACTION_TEXTOUTPUT, STRING_ALREADYOFF},
    {VERB_WEARPANTS, ACTION_GOTOSTATE, STATE_DOOROPEN},
    {VERB_WEARPANTS, ACTION_TEXTOUTPUT, STRING_WEARPANTS },
    {VERB_OPENDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_PULLDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_CLOSEDOOR, ACTION_GOTOSTATE, STATE_STANDINGPANTSOFF},
    {VERB_CLOSEDOOR, ACTION_TEXTOUTPUT, STRING_CLOSEDOOR},
    {VERB_SITTOILET, ACTION_GOTOSTATE, STATE_ONTOILETPANTSOFF},
    {VERB_SITTOILET, ACTION_TEXTOUTPUT, STRING_SITONTOILET},
    {VERB_STAND, ACTION_TEXTOUTPUT, STRING_STANDMORE},
    {VERB_LOOK, ACTION_TEXTOUTPUT, STRING_LOOKNOPANTSDOOROPEN},
    {VERB_LOOKWASHROOM, ACTION_TEXTOUTPUT, STRING_LOOKWASHROOM},
    {VERB_LOOKDOOR, ACTION_TEXTOUTPUT, STRING_LOOKDOOR},
    {VERB_LOOKTOILET, ACTION_TEXTOUTPUT, STRING_LOOKTOILET},
    {VERB_TIMEOUT, ACTION_GOTOSTATE, STATE_TIMEOVERSTANDINGPANTSOFF },
    {VERB_PILLSACTIVE, ACTION_GOTOSTATE, STATE_PILLSSTANDINGPANTSOFF1},
    {0,0,0}
};

GameAction ACTIONS_ONTOILET[] = {
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_ONTOILET},
    {VERB_SHIT, ACTION_GOTOSTATE, STATE_SHITINPANTSSITTING},
    {VERB_SHITPANTS, ACTION_GOTOSTATE, STATE_SHITINPANTSSITTING},
    {VERB_FART, ACTION_GOTOSTATE, STATE_FARTPANTSONSITTING},
    {VERB_SHITTOILET, ACTION_GOTOSTATE, STATE_SHITINPANTSSITTING},
    {VERB_DONTSHIT, ACTION_GOTOSTATE, STATE_DONTSHITPANTSONSITTING},
    {VERB_BREAK, ACTION_TEXTOUTPUT, STRING_CONCENTRATE},
    {VERB_DIE, ACTION_GOTOSTATE, STATE_DIEPANTSONSITTING},
    {VERB_REMOVEPANTS, ACTION_TEXTOUTPUT, STRING_GETOFFTOILET},
    {VERB_WEARPANTS, ACTION_TEXTOUTPUT, STRING_ALREADYON },
    {VERB_OPENDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_PULLDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_CLOSEDOOR, ACTION_TEXTOUTPUT, STRING_CANTREACH},
    {VERB_SITTOILET, ACTION_TEXTOUTPUT, STRING_ALREADYSITTING},
    {VERB_STAND, ACTION_GOTOSTATE, STATE_DOOROPEN},
    {VERB_STAND, ACTION_TEXTOUTPUT, STRING_STAND},
    {VERB_LOOK, ACTION_TEXTOUTPUT, STRING_LOOKDOOROPEN},
    {VERB_LOOKWASHROOM, ACTION_TEXTOUTPUT, STRING_LOOKWASHROOM},
    {VERB_LOOKDOOR, ACTION_TEXTOUTPUT, STRING_LOOKDOOR},
    {VERB_LOOKTOILET, ACTION_TEXTOUTPUT, STRING_LOOKTOILET},
    {VERB_TIMEOUT, ACTION_GOTOSTATE, STATE_TIMEOVERSITTINGPANTSON },
    {VERB_PILLSACTIVE, ACTION_GOTOSTATE, STATE_PILLSSITTINGPANTSON1},
    {0,0,0}
};


GameAction ACTIONS_ONTOILETPANTSOFF[] = {
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_ONTOILETPANTSOFF},
    {VERB_SHIT, ACTION_GOTOSTATE, STATE_SHITINTOILET},
    {VERB_SHITPANTS, ACTION_GOTOSTATE, STATE_SHITINPANTSWHILEOFF},
    {VERB_FART, ACTION_GOTOSTATE, STATE_SHITINTOILET},
    {VERB_SHITTOILET, ACTION_GOTOSTATE, STATE_SHITINTOILET},
    {VERB_DONTSHIT, ACTION_GOTOSTATE, STATE_DONTSHITPANTSOFFSITTING},
    {VERB_BREAK, ACTION_TEXTOUTPUT, STRING_CONCENTRATE},
    {VERB_DIE, ACTION_GOTOSTATE, STATE_DIEPANTSOFFSITTING},
    {VERB_REMOVEPANTS, ACTION_TEXTOUTPUT, STRING_ALREADYOFF},
    {VERB_WEARPANTS, ACTION_TEXTOUTPUT, STRING_GETOFFTOILET },
    {VERB_OPENDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_PULLDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_CLOSEDOOR, ACTION_TEXTOUTPUT, STRING_CANTREACH},
    {VERB_SITTOILET, ACTION_TEXTOUTPUT, STRING_ALREADYSITTING},
    {VERB_STAND, ACTION_GOTOSTATE, STATE_DOOROPENPANTSOFF},
    {VERB_STAND, ACTION_TEXTOUTPUT, STRING_STAND},
    {VERB_LOOK, ACTION_TEXTOUTPUT, STRING_LOOKNOPANTSDOOROPEN},
    {VERB_LOOKWASHROOM, ACTION_TEXTOUTPUT, STRING_LOOKWASHROOM},
    {VERB_LOOKDOOR, ACTION_TEXTOUTPUT, STRING_LOOKDOOR},
    {VERB_LOOKTOILET, ACTION_TEXTOUTPUT, STRING_LOOKTOILET},
    {VERB_TIMEOUT, ACTION_GOTOSTATE, STATE_TIMEOVERSITTINGPANTSOFF },
    {VERB_PILLSACTIVE, ACTION_GOTOSTATE, STATE_PILLSSITTINGPANTSOFF1},
    {0,0,0}
};

GameAction ACTIONS_SHITONFLOOR[] = {
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITONFLOOR},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_SHITONFLOOR},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0,0,0}
};

GameAction ACTIONS_SHITINTOILET[] = {
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINTOILET},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_SHITINTOILET},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0,0,0}
};

GameAction ACTIONS_SHITPANTSSTANDING[] = {
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITPANTSSTANDING},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_SHITPANTSSTANDING},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0,0,0}
};

GameAction ACTIONS_SHITINPANTSSITTING[] = {
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINPANTSSITTING},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_SHITINPANTSSITTING},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0,0,0}
};

GameState GameStates[] = {
    {0, 0},
    {STATE_MENU, ACTIONS_MENU},
    {STATE_STANDING, ACTIONS_STANDING},
    {STATE_STANDINGPANTSOFF, ACTIONS_STANDINGPANTSOFF},
    {STATE_DOOROPEN, ACTIONS_DOOROPEN},
    {STATE_DOOROPENPANTSOFF, ACTIONS_DOOROPENPANTSOFF},
    {STATE_ONTOILET, ACTIONS_ONTOILET},
    {STATE_ONTOILETPANTSOFF, ACTIONS_ONTOILETPANTSOFF},

    {STATE_AWARDS, NULL},
    {STATE_CREDITS, NULL},

    //endings
    {STATE_SHITONFLOOR, ACTIONS_SHITONFLOOR},
    {STATE_SHITINTOILET, ACTIONS_SHITINTOILET},
    {STATE_SHITPANTSSTANDING, ACTIONS_SHITPANTSSTANDING},
    {STATE_SHITINPANTSSITTING, ACTIONS_SHITINPANTSSITTING},
/*    {STATE_DONTSHITPANTSON, ACTIONS_DONTSHITPANTSON},
    {STATE_BREAKPANTSON, ACTIONS_BREAKPANTSON},
    {STATE_FARTPANTSON, ACTIONS_FARTPANTSON},
    {STATE_FARTPANTSOFF, ACTIONS_FARTPANTSOFF},
    {STATE_DIEPANTSON ,ACTIONS_DIEPANTSON},
    {STATE_DIEPANTSOFF ,ACTIONS_DIEPANTSOFF},
    {STATE_DONTSHITPANTSOFF ,ACTIONS_DONTSHITPANTSOFF},
    {STATE_BREAKPANTSOFF ,ACTIONS_BREAKPANTSOFF},
    {STATE_PILLSSTANDINGPANTSON1 ,ACTIONS_PILLSSTANDINGPANTSON1},
    {STATE_PILLSSTANDINGPANTSON2 ,ACTIONS_PILLSSTANDINGPANTSON2},
    {STATE_PILLSSTANDINGPANTSON3 ,ACTIONS_PILLSSTANDINGPANTSON3},
    {STATE_NULL,ACTIONS_NULL},
    {STATE_STARTINGGUN ,ACTIONS_STARTINGGUN},
    {STATE_PILLSSTANDINGPANTSOFF1 ,ACTIONS_PILLSSTANDINGPANTSOFF1},
    {STATE_PILLSSTANDINGPANTSOFF2 ,ACTIONS_PILLSSTANDINGPANTSOFF2},
    {STATE_PILLSSTANDINGPANTSOFF3 ,ACTIONS_PILLSSTANDINGPANTSOFF3},
    {STATE_PILLSSITTINGPANTSON1 ,ACTIONS_PILLSSITTINGPANTSON1},
    {STATE_PILLSSITTINGPANTSON2 ,ACTIONS_PILLSSITTINGPANTSON2},
    {STATE_PILLSSITTINGPANTSON3 ,ACTIONS_PILLSSITTINGPANTSON3},
    {STATE_PILLSSITTINGPANTSOFF1 ,ACTIONS_PILLSSITTINGPANTSOFF1},
    {STATE_PILLSSITTINGPANTSOFF2 ,ACTIONS_PILLSSITTINGPANTSOFF2},
    {STATE_PILLSSITTINGPANTSOFF3 ,ACTIONS_PILLSSITTINGPANTSOFF3},
    {STATE_TIMEOVERSTANDINGPANTSON ,ACTIONS_TIMEOVERSTANDINGPANTSON},
    {STATE_TIMEOVERSITTINGPANTSON ,ACTIONS_TIMEOVERSITTINGPANTSON},
    {STATE_TIMEOVERSTANDINGPANTSOFF ,ACTIONS_TIMEOVERSTANDINGPANTSOFF},
    {STATE_TIMEOVERSITTINGPANTSOFF ,ACTIONS_TIMEOVERSITTINGPANTSOFF},
    {STATE_SHITINPANTSWHILEOFF ,ACTIONS_SHITINPANTSWHILEOFF},
    {STATE_FARTPANTSONSITTING ,ACTIONS_FARTPANTSONSITTING},
    {STATE_DONTSHITPANTSONSITTING ,ACTIONS_DONTSHITPANTSONSITTING},
    {STATE_DIEPANTSONSITTING ,ACTIONS_DIEPANTSONSITTING},
    {STATE_DIEPANTSOFFSITTING ,ACTIONS_DIEPANTSOFFSITTING},
    {STATE_DONTSHITPANTSOFFSITTING ,ACTIONS_DONTSHITPANTSOFFSITTING},*/
};

char * FindString(int id){

    GameString *currstring = GameStrings;

    while (currstring != NULL){

        if (currstring->ID == id){
            return currstring->Text;
        }

        currstring = currstring->next;
    }

    return NULL;
}

int FindVerb(char *TextEntry){

    GameVerb *currverb = NULL;
    Synonym *currsyn = NULL;

    currverb = firstverb;
    while (currverb != NULL){

        currsyn = currverb->Synonyms;
        while (currsyn != NULL) {

            if (strcmp(currsyn->Text, TextEntry) == 0)
                return currverb->ID;

            currsyn = currsyn->next;
        }

        currverb = currverb->next;
    }

    DisplayText("Can't find verb");
    return 0;
}

char filter[3] = {'\r', '\n', 0x00};

void LoadVerbs() {

    char line[1024];

    int linenum = 1;

    GameString *currstring;
    GameString *prevstring = NULL;

    Synonym *prevsyn = NULL, *currsyn = NULL;
    GameVerb *prevverb = NULL, *currverb = NULL;
    char *token;
    char *pnt;
    FILE* file = fopen("strings.txt", "r");

    while (fgets(line, 1024, file)) {

        // one string per line
        currstring = malloc(sizeof(GameVerb));
        currstring->ID = linenum;
        currstring->next = NULL;

        currstring->Text = malloc(strlen(line) + 1);
        strcpy(currstring->Text, line);
        currstring->Text[strcspn(currstring->Text, filter)] = 0; // strip newline

        if (prevstring != NULL)
            prevstring->next = currstring;

        if (GameStrings == NULL)
            GameStrings = currstring;

        prevstring = currstring;
        linenum++;
    }

    fclose(file);

    file = fopen("verbs.txt", "r");

    linenum = 1;
    while (fgets(line, 1024, file))
    {
        // one verb per line
        currverb = malloc(sizeof(GameVerb));
        currverb->ID = linenum;
        currverb->Synonyms = NULL;
        currverb->next = NULL;

        if (firstverb == NULL)
            firstverb = currverb;

        if (prevverb != NULL)
            prevverb->next = currverb;
        
        // Get the first token
        token = strtok(line, ",");

        prevsyn = NULL;
        
        // Walk through other tokens
        while(token != NULL) {

            // alloc a synonym
            currsyn = malloc(sizeof(Synonym));
            currsyn->next = NULL;

            // if first one, link it into verb
            if (currverb->Synonyms == NULL)
                currverb->Synonyms = currsyn;

            currsyn->Text = malloc(strlen(token) + 1);

            strcpy(currsyn->Text, token);
            currsyn->Text[strcspn(currsyn->Text, filter)] = 0; // strip newline


            /*pnt = currsyn->Text;
            while (*pnt != 0){
                printf("%02X", *pnt);
                pnt++;
            }

            printf(" -- %s\n", token);*/

            if (prevsyn != NULL)
                prevsyn->next = currsyn;

            prevsyn = currsyn;

            token = strtok(NULL, ","); // Subsequent calls
            
        }

        prevverb = currverb;

        linenum++;
    }

    fclose(file);

   
    currverb = firstverb;
    while (currverb != NULL) {

        printf("%d\n", currverb->ID);
        currsyn = currverb->Synonyms;
        while (currsyn != NULL){
            pnt = currsyn->Text;
            while (*pnt != 0){
                printf("%02X", *pnt);
                pnt++;
            }
            printf(" --- %s\n", currsyn->Text);
            currsyn = currsyn->next;
        }

        currverb = currverb->next;
    }
}

GameState *CurrState = &GameStates[1];

void RunAction(GameAction *curraction){

    GameAction *StateEntryAction = NULL;

    switch (curraction->Type) {
        case ACTION_TEXTOUTPUT:
            //printf("printf string %d\n", curraction->Action);
            //printf("%s\n", FindString(curraction->Action));
            DisplayText(FindString(curraction->Action));
            break;
        case ACTION_SCREENLINES:
            split_rows = curraction->Action;
            break;
        case ACTION_DISPLAYGFX:
            //printf("display gfx %d\n", curraction->Action);
            DisplayGFX(curraction->Action);
            break;
        case ACTION_GOTOSTATE:
            //printf("goto state %d\n", curraction->Action);
            CurrState = &GameStates[curraction->Action];

            // run any "on entry" actions in the new state
            StateEntryAction = CurrState->Actions;
            while (StateEntryAction->Verb != 0) {
                if (StateEntryAction->Verb == VERB_ONENTRY){
                    RunAction(StateEntryAction);
                }
                StateEntryAction++;
            }
            break;

        case ACTION_DRAWMENU:
            DrawTextColor(55, 21, 0x09, "A survival horror game");
            DrawTextColor(2, 23, 0x0f, "Instructions :");
            DrawTextColor(2, 24, 0x0f, "- To start type \"play\"");
            DrawTextColor(2, 25, 0x0f, "- To view achievements type \"awards\"");
            DrawTextColor(2, 27, 0x0f, "Goal :");
            DrawTextColor(2, 28, 0x0f, "- Don't shit your pants");
            DrawTextColor(2, 30, 0x0f, "- Type \"delete\" to delete your file");
            break;


    }
}

void RunVerb(int Verb) {
    GameAction *curraction = CurrState->Actions;
    while (curraction->Verb != 0) {

        if (curraction->Verb == VERB_WILDCARD || curraction->Verb == Verb) {
            RunAction(curraction);
        }

        curraction++;
    }
}

void Gamelogic_Init(){
    LoadVerbs();
}

void GameLogic_TextInput(char *Text) {
    RunVerb(FindVerb(Text));
}



/*int main(void)
{   
    char inbuf[100];


    while(1) {
        fgets(inbuf, 100, stdin);
        inbuf[strcspn(inbuf, "\r\n")] = 0; // strip newline
        printf("inputted %s\n", inbuf);
        //printf("verb ID %d\n",FindVerb(inbuf));
        RunVerb(FindVerb(inbuf));
    }

    return 0;
}*/