#include <stdio.h>
#include <dos.h>
#include <conio.h>
#include <string.h>
#include <stdlib.h>
#include "gamelogic.h"

GameVerb *firstverb = NULL;
GameString *GameStrings = NULL;
unsigned char pillstaken = 0;
int Countdown = 40;
int PillCountdown = 0;
int FartCount = 0;

unsigned int Awards = 0;

unsigned int NoteTable[] = {
    145940,
    137749,
    130018,
    122721,
    115833,
    109332,
    103196,
    97404,
    91937,
    86777,
    81906,
    77309,
    72970,
    68875,
    65009,
    61360,
    57917,
    54666,
    51598,
    48702,
    45968,
    43388,
    40953,
    38655,
    36485,
    34437,
    32505,
    30680,
    28958,
    27333,
    25799,
    24351,
    22984,
    21694,
    20477,
    19327,
    18243,
    17219,
    16252,
    15340,
    14479,
    13666,
    12899,
    12175,
    11492,
    10847,
    10238,
    9664,
    9121,
    8609,
    8126,
    7670,
    7240,
    6833,
    6450,
    6088,
    5746,
    5424,
    5119,
    4832,
    4561,
    4305,
    4063,
    3835,
    3620,
    3417,
    3225,
    3044,
    2873,
    2712,
    2560,
    2416,
    2280,
    2152,
    2032,
    1918,
    1810,
    1708,
    1612,
    1522,
    1437,
    1356,
    1280,
    1208,
    1140,
    1076,
    1016,
    959,
    905,
    854,
    806,
    761,
    718,
    678,
    640,
    604,
    570,
    538,
    508,
    479,
    452,
    427,
    403,
    380,
    359,
    339,
    320,
    302,
    285,
    269,
    254,
    240,
    226,
    214,
    202,
    190,
    180,
    169,
    160,
    151,
    143,
    135,
    127,
    120,
    113,
    107,
    101,
    95
};



Note SONG_INTRO[] = {

    {0, 44},
    {600, 255},
    {750, 38},
    {1200, 41},
    {1500, 40},
    {1800, 255},
    {2100, 36},
    {2500, 39},
    {2850, 38},
    {3150, 255},
    {3450, 33},
    {3900, 36},
    {4200, 35},
    {4500, 255},
    {4800, 31},
    {5250, 255},
    {5400, 33},
    {6000, 255},
    {0, 0}
};

GameAction ACTIONS_MENU[] = {

    {VERB_ONENTRY, ACTION_DISPLAYNEWAWARDS, 0},

    {VERB_ONENTRY, ACTION_SCREENLINES, 20},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_MENU},
    {VERB_ONENTRY, ACTION_SETTEXTLINE, 32},
    {VERB_ONENTRY, ACTION_DRAWMENU, 0},

    {VERB_PLAY, ACTION_GOTOSTATE, STATE_STANDING},
    {VERB_PLAY, ACTION_TEXTOUTPUT, STRING_REALLYNEEDSHIT},
    {VERB_PLAY, ACTION_FART, 0},
    {VERB_PLAY, ACTION_TAKEPILLS, 0},
    {VERB_PLAY, ACTION_ADDTOTIMER, 0},

    {VERB_DELETE, ACTION_DELETEAWARDS, 0},
    {VERB_DELETE, ACTION_GOTOSTATE, STATE_STANDING},
    {VERB_AWARDS, ACTION_GOTOSTATE, STATE_AWARDS},
    {VERB_MENU, ACTION_TEXTOUTPUT, STRING_ALREADYMENU},
    {VERB_QUIT, ACTION_EXITGAME, 0},
    {VERB_IDIOT, ACTION_TEXTOUTPUT, STRING_IDIOT},
    {VERB_CREDITS, ACTION_GOTOSTATE, STATE_CREDITS},
    {VERB_SHIT, ACTION_GOTOSTATE, STATE_STARTINGGUN},
    {0, 0, 0}
};

GameAction ACTIONS_AWARDS[] = {

    {VERB_ONENTRY, ACTION_SCREENLINES, 14},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_AWARDS},
    {VERB_ONENTRY, ACTION_SETTEXTLINE, 40},
    {VERB_ONENTRY, ACTION_DRAWMENU, 1},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}
};

GameAction ACTIONS_STANDING[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 86},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_STANDING},

    {VERB_SHIT, ACTION_GOTOSTATE, STATE_SHITPANTSSTANDING},
    {VERB_SHITPANTS, ACTION_GOTOSTATE, STATE_SHITPANTSSTANDING},
    {VERB_FART, ACTION_GOTOSTATE, STATE_FARTPANTSON},
    {VERB_FARTLIGHTLY3, ACTION_GOTOSTATE, STATE_SHITPANTSSTANDING},
    {VERB_SHITTOILET, ACTION_TEXTOUTPUT, STRING_WHATTOILET},
    {VERB_DONTSHIT, ACTION_GOTOSTATE, STATE_DONTSHITPANTSON},
    {VERB_BREAK, ACTION_GOTOSTATE, STATE_BREAKPANTSON},
    {VERB_DIE, ACTION_GOTOSTATE, STATE_DIEPANTSON},

    {VERB_REMOVEPANTS, ACTION_GOTOSTATE, STATE_STANDINGPANTSOFF},
    {VERB_REMOVEPANTS, ACTION_TEXTOUTPUT, STRING_REMOVEPANTS},

    {VERB_WEARPANTS, ACTION_TEXTOUTPUT, STRING_ALREADYON},
    {VERB_OPENDOOR, ACTION_TEXTOUTPUT, STRING_PUSHDOOR},
    
    {VERB_PULLDOOR, ACTION_GOTOSTATE, STATE_DOOROPEN},
    {VERB_PULLDOOR, ACTION_TEXTOUTPUT, STRING_PULLDOOR},
    {VERB_CLOSEDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYCLOSED},
    {VERB_SITTOILET, ACTION_TEXTOUTPUT, STRING_CANTSIT},
    {VERB_STAND, ACTION_TEXTOUTPUT, STRING_STANDMORE},
    {VERB_LOOK, ACTION_TEXTOUTPUT, STRING_LOOK},
    {VERB_LOOKWASHROOM, ACTION_TEXTOUTPUT, STRING_CANTSEE},
    {VERB_LOOKDOOR, ACTION_TEXTOUTPUT, STRING_LOOKDOOR},
    {VERB_LOOKTOILET, ACTION_TEXTOUTPUT, STRING_WHATTOILET},
    {VERB_TIMEOUT, ACTION_GOTOSTATE, STATE_TIMEOVERSTANDINGPANTSON},
    {VERB_PILLSACTIVE, ACTION_GOTOSTATE, STATE_PILLSSTANDINGPANTSON1},
    {0, 0, 0}};

GameAction ACTIONS_STANDINGPANTSOFF[] = {
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_STANDINGPANTSOFF},
    {VERB_SHIT, ACTION_GOTOSTATE, STATE_SHITONFLOOR},
    {VERB_SHITPANTS, ACTION_GOTOSTATE, STATE_SHITINPANTSWHILEOFF},
    {VERB_FART, ACTION_GOTOSTATE, STATE_FARTPANTSOFF},
    {VERB_FARTLIGHTLY3, ACTION_GOTOSTATE, STATE_SHITONFLOOR},
    {VERB_SHITTOILET, ACTION_TEXTOUTPUT, STRING_WHATTOILET},
    {VERB_DONTSHIT, ACTION_GOTOSTATE, STATE_DONTSHITPANTSOFF},
    {VERB_BREAK, ACTION_GOTOSTATE, STATE_BREAKPANTSOFF},
    {VERB_DIE, ACTION_GOTOSTATE, STATE_DIEPANTSOFF},
    {VERB_REMOVEPANTS, ACTION_TEXTOUTPUT, STRING_ALREADYOFF},
    {VERB_WEARPANTS, ACTION_GOTOSTATE, STATE_STANDING},
    {VERB_WEARPANTS, ACTION_TEXTOUTPUT, STRING_WEARPANTS},
    {VERB_OPENDOOR, ACTION_TEXTOUTPUT, STRING_PUSHDOOR},
    {VERB_PULLDOOR, ACTION_GOTOSTATE, STATE_DOOROPENPANTSOFF},
    {VERB_PULLDOOR, ACTION_TEXTOUTPUT, STRING_PULLDOOR},
    {VERB_CLOSEDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYCLOSED},
    {VERB_SITTOILET, ACTION_TEXTOUTPUT, STRING_CANTSIT},
    {VERB_STAND, ACTION_TEXTOUTPUT, STRING_STANDMORE},
    {VERB_LOOK, ACTION_TEXTOUTPUT, STRING_LOOKNOPANTS},
    {VERB_LOOKWASHROOM, ACTION_TEXTOUTPUT, STRING_CANTSEE},
    {VERB_LOOKDOOR, ACTION_TEXTOUTPUT, STRING_LOOKDOOR},
    {VERB_LOOKTOILET, ACTION_TEXTOUTPUT, STRING_WHATTOILET},
    {VERB_TIMEOUT, ACTION_GOTOSTATE, STATE_TIMEOVERSTANDINGPANTSOFF},
    {VERB_PILLSACTIVE, ACTION_GOTOSTATE, STATE_PILLSSTANDINGPANTSOFF1},
    {0, 0, 0}};

GameAction ACTIONS_DOOROPEN[] = {
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_DOOROPEN},
    {VERB_SHIT, ACTION_GOTOSTATE, STATE_SHITPANTSSTANDING},
    {VERB_FARTLIGHTLY3, ACTION_GOTOSTATE, STATE_SHITPANTSSTANDING},
    {VERB_SHITPANTS, ACTION_GOTOSTATE, STATE_SHITPANTSSTANDING},
    {VERB_FART, ACTION_GOTOSTATE, STATE_FARTPANTSON},
    {VERB_SHITTOILET, ACTION_GOTOSTATE, STATE_SHITINPANTSSITTING},
    {VERB_DONTSHIT, ACTION_GOTOSTATE, STATE_DONTSHITPANTSON},
    {VERB_BREAK, ACTION_GOTOSTATE, STATE_BREAKPANTSON},
    {VERB_DIE, ACTION_GOTOSTATE, STATE_DIEPANTSON},
    {VERB_REMOVEPANTS, ACTION_GOTOSTATE, STATE_DOOROPENPANTSOFF},
    {VERB_REMOVEPANTS, ACTION_TEXTOUTPUT, STRING_REMOVEPANTS},
    {VERB_WEARPANTS, ACTION_TEXTOUTPUT, STRING_ALREADYON},
    {VERB_OPENDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_PULLDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_CLOSEDOOR, ACTION_GOTOSTATE, STATE_STANDING},
    {VERB_CLOSEDOOR, ACTION_TEXTOUTPUT, STRING_CLOSEDOOR},
    {VERB_SITTOILET, ACTION_GOTOSTATE, STATE_ONTOILET},
    {VERB_SITTOILET, ACTION_TEXTOUTPUT, STRING_SITONTOILET},
    {VERB_STAND, ACTION_TEXTOUTPUT, STRING_STANDMORE},
    {VERB_LOOK, ACTION_TEXTOUTPUT, STRING_LOOKDOOROPEN},
    {VERB_LOOKWASHROOM, ACTION_TEXTOUTPUT, STRING_LOOKWASHROOM},
    {VERB_LOOKDOOR, ACTION_TEXTOUTPUT, STRING_LOOKDOOR},
    {VERB_LOOKTOILET, ACTION_TEXTOUTPUT, STRING_LOOKTOILET},
    {VERB_TIMEOUT, ACTION_GOTOSTATE, STATE_TIMEOVERSTANDINGPANTSON},
    {VERB_PILLSACTIVE, ACTION_GOTOSTATE, STATE_PILLSSTANDINGPANTSON1},
    {0, 0, 0}};

GameAction ACTIONS_DOOROPENPANTSOFF[] = {
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_DOOROPENPANTSOFF},
    {VERB_SHIT, ACTION_GOTOSTATE, STATE_SHITONFLOOR},
    {VERB_FARTLIGHTLY3, ACTION_GOTOSTATE, STATE_SHITONFLOOR},
    {VERB_SHITPANTS, ACTION_GOTOSTATE, STATE_SHITINPANTSWHILEOFF},
    {VERB_FART, ACTION_GOTOSTATE, STATE_FARTPANTSOFF},
    {VERB_SHITTOILET, ACTION_GOTOSTATE, STATE_SHITINTOILET},
    {VERB_DONTSHIT, ACTION_GOTOSTATE, STATE_DONTSHITPANTSOFF},
    {VERB_BREAK, ACTION_GOTOSTATE, STATE_BREAKPANTSOFF},
    {VERB_DIE, ACTION_GOTOSTATE, STATE_DIEPANTSOFF},
    {VERB_REMOVEPANTS, ACTION_TEXTOUTPUT, STRING_ALREADYOFF},
    {VERB_WEARPANTS, ACTION_GOTOSTATE, STATE_DOOROPEN},
    {VERB_WEARPANTS, ACTION_TEXTOUTPUT, STRING_WEARPANTS},
    {VERB_OPENDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_PULLDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_CLOSEDOOR, ACTION_GOTOSTATE, STATE_STANDINGPANTSOFF},
    {VERB_CLOSEDOOR, ACTION_TEXTOUTPUT, STRING_CLOSEDOOR},
    {VERB_SITTOILET, ACTION_GOTOSTATE, STATE_ONTOILETPANTSOFF},
    {VERB_SITTOILET, ACTION_TEXTOUTPUT, STRING_SITONTOILET},
    {VERB_STAND, ACTION_TEXTOUTPUT, STRING_STANDMORE},
    {VERB_LOOK, ACTION_TEXTOUTPUT, STRING_LOOKNOPANTSDOOROPEN},
    {VERB_LOOKWASHROOM, ACTION_TEXTOUTPUT, STRING_LOOKWASHROOM},
    {VERB_LOOKDOOR, ACTION_TEXTOUTPUT, STRING_LOOKDOOR},
    {VERB_LOOKTOILET, ACTION_TEXTOUTPUT, STRING_LOOKTOILET},
    {VERB_TIMEOUT, ACTION_GOTOSTATE, STATE_TIMEOVERSTANDINGPANTSOFF},
    {VERB_PILLSACTIVE, ACTION_GOTOSTATE, STATE_PILLSSTANDINGPANTSOFF1},
    {0, 0, 0}};

GameAction ACTIONS_ONTOILET[] = {
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_ONTOILET},
    {VERB_SHIT, ACTION_GOTOSTATE, STATE_SHITINPANTSSITTING},
    {VERB_FARTLIGHTLY3, ACTION_GOTOSTATE, STATE_SHITINPANTSSITTING},
    {VERB_SHITPANTS, ACTION_GOTOSTATE, STATE_SHITINPANTSSITTING},
    {VERB_FART, ACTION_GOTOSTATE, STATE_FARTPANTSONSITTING},
    {VERB_SHITTOILET, ACTION_GOTOSTATE, STATE_SHITINPANTSSITTING},
    {VERB_DONTSHIT, ACTION_GOTOSTATE, STATE_DONTSHITPANTSONSITTING},
    {VERB_BREAK, ACTION_TEXTOUTPUT, STRING_CONCENTRATE},
    {VERB_DIE, ACTION_GOTOSTATE, STATE_DIEPANTSONSITTING},
    {VERB_REMOVEPANTS, ACTION_TEXTOUTPUT, STRING_GETOFFTOILET},
    {VERB_WEARPANTS, ACTION_TEXTOUTPUT, STRING_ALREADYON},
    {VERB_OPENDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_PULLDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_CLOSEDOOR, ACTION_TEXTOUTPUT, STRING_CANTREACH},
    {VERB_SITTOILET, ACTION_TEXTOUTPUT, STRING_ALREADYSITTING},
    {VERB_STAND, ACTION_GOTOSTATE, STATE_DOOROPEN},
    {VERB_STAND, ACTION_TEXTOUTPUT, STRING_STAND},
    {VERB_LOOK, ACTION_TEXTOUTPUT, STRING_LOOKDOOROPEN},
    {VERB_LOOKWASHROOM, ACTION_TEXTOUTPUT, STRING_LOOKWASHROOM},
    {VERB_LOOKDOOR, ACTION_TEXTOUTPUT, STRING_LOOKDOOR},
    {VERB_LOOKTOILET, ACTION_TEXTOUTPUT, STRING_LOOKTOILET},
    {VERB_TIMEOUT, ACTION_GOTOSTATE, STATE_TIMEOVERSITTINGPANTSON},
    {VERB_PILLSACTIVE, ACTION_GOTOSTATE, STATE_PILLSSITTINGPANTSON1},
    {0, 0, 0}};

GameAction ACTIONS_ONTOILETPANTSOFF[] = {
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_ONTOILETPANTSOFF},
    {VERB_SHIT, ACTION_GOTOSTATE, STATE_SHITINTOILET},
    {VERB_FARTLIGHTLY3, ACTION_GOTOSTATE, STATE_SHITINTOILET},
    {VERB_SHITPANTS, ACTION_GOTOSTATE, STATE_SHITINPANTSWHILEOFF},
    {VERB_FART, ACTION_GOTOSTATE, STATE_SHITINTOILET},
    {VERB_SHITTOILET, ACTION_GOTOSTATE, STATE_SHITINTOILET},
    {VERB_DONTSHIT, ACTION_GOTOSTATE, STATE_DONTSHITPANTSOFFSITTING},
    {VERB_BREAK, ACTION_TEXTOUTPUT, STRING_CONCENTRATE},
    {VERB_DIE, ACTION_GOTOSTATE, STATE_DIEPANTSOFFSITTING},
    {VERB_REMOVEPANTS, ACTION_TEXTOUTPUT, STRING_ALREADYOFF},
    {VERB_WEARPANTS, ACTION_TEXTOUTPUT, STRING_GETOFFTOILET},
    {VERB_OPENDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_PULLDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_CLOSEDOOR, ACTION_TEXTOUTPUT, STRING_CANTREACH},
    {VERB_SITTOILET, ACTION_TEXTOUTPUT, STRING_ALREADYSITTING},
    {VERB_STAND, ACTION_GOTOSTATE, STATE_DOOROPENPANTSOFF},
    {VERB_STAND, ACTION_TEXTOUTPUT, STRING_STAND},
    {VERB_LOOK, ACTION_TEXTOUTPUT, STRING_LOOKNOPANTSDOOROPEN},
    {VERB_LOOKWASHROOM, ACTION_TEXTOUTPUT, STRING_LOOKWASHROOM},
    {VERB_LOOKDOOR, ACTION_TEXTOUTPUT, STRING_LOOKDOOR},
    {VERB_LOOKTOILET, ACTION_TEXTOUTPUT, STRING_LOOKTOILET},
    {VERB_TIMEOUT, ACTION_GOTOSTATE, STATE_TIMEOVERSITTINGPANTSOFF},
    {VERB_PILLSACTIVE, ACTION_GOTOSTATE, STATE_PILLSSITTINGPANTSOFF1},
    {0, 0, 0}};

GameAction ACTIONS_SHITONFLOOR[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITONFLOOR},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_SHITONFLOOR},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_SHITONFLOOR},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_SHITINTOILET[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINTOILET},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_SHITINTOILET},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_SHITINTOILET},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_SHITPANTSSTANDING[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITPANTSSTANDING},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_SHITPANTSSTANDING},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_SHITINPANTSSTANDING},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_SHITINPANTSSITTING[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINPANTSSITTING},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_SHITINPANTSSITTING},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_SHITINPANTSSITTING},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_BREAKPANTSON[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITPANTSSTANDING},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_BREAKPANTSON},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_SHITINPANTSSTANDING},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}
};

GameAction ACTIONS_BREAKPANTSOFF[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITONFLOOR},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_BREAKPANTSOFF},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_FARTPANTSON[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITPANTSSTANDING},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_FARTPANTSON},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_FARTPANTSOFF[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITONFLOOR},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_FARTPANTSOFF},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_DIEPANTSON[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_DIEPANTSON},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_DIEPANTSON},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_DIE},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_DIEPANTSOFF[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_DIEPANTSOFF},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_DIEPANTSOFF},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_DIE},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_DIEPANTSONSITTING[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_DIEPANTSONSITTING},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_DIEPANTSONSITTING},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_DIE},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_DIEPANTSOFFSITTING[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_DIEPANTSOFFSITTING},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_DIEPANTSOFFSITTING},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_DIE},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_DONTSHITPANTSON[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITPANTSSTANDING},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_DONTSHITPANTSON},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_DONTSHITPANTSOFF[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITONFLOOR},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_DONTSHITPANTSOFF},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_DONTSHITPANTSONSITTING[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINPANTSSITTING},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_DONTSHITPANTSONSITTING},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_DONTSHITPANTSOFFSITTING[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINTOILET},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_DONTSHITPANTSOFFSITTING},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSTANDINGPANTSON1[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_PILLSSTANDINGPANTSON1},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSTANDINGPANTSON1},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_PILLSKICKIN},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_PILLSSTANDINGPANTSON2},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSTANDINGPANTSON2[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_PILLSSTANDINGPANTSON2},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSTANDINGPANTSON2},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_PILLSSTANDINGPANTSON3},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSTANDINGPANTSON3[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITPANTSSTANDING},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSTANDINGPANTSON3},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_PILLSFAIL},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSTANDINGPANTSOFF1[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_PILLSSTANDINGPANTSON1},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSTANDINGPANTSOFF1},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_PILLSKICKIN},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_PILLSSTANDINGPANTSOFF2},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSTANDINGPANTSOFF2[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_PILLSSTANDINGPANTSON2},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSTANDINGPANTSOFF2},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_PILLSSTANDINGPANTSOFF3},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSTANDINGPANTSOFF3[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITONFLOOR},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSTANDINGPANTSOFF3},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSITTINGPANTSON1[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_PILLSSITTINGPANTSON1},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSITTINGPANTSON1},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_PILLSSITTINGPANTSON2},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_PILLSKICKIN},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSITTINGPANTSON2[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_PILLSSITTINGPANTSON2},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSITTINGPANTSON2},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_PILLSSITTINGPANTSON3},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSITTINGPANTSON3[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINPANTSSITTING},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSITTINGPANTSON3},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_PILLSFAIL},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSITTINGPANTSOFF1[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINTOILET},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSITTINGPANTSOFF1},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_PILLSSITTINGPANTSOFF2},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_PILLSKICKIN},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSITTINGPANTSOFF2[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_PILLSSITTINGPANTSOFF2},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSITTINGPANTSOFF2},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_PILLSSITTINGPANTSOFF3},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSITTINGPANTSOFF3[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINTOILET},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSITTINGPANTSOFF3},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_TIMEOVERSTANDINGPANTSON[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITPANTSSTANDING},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_TIMEOVERSTANDINGPANTSON},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_TIMEOVER},
    {0, 0, 0}};

GameAction ACTIONS_TIMEOVERSTANDINGPANTSOFF[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITONFLOOR},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_TIMEOVERSTANDINGPANTSOFF},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_TIMEOVER},
    {0, 0, 0}};

GameAction ACTIONS_TIMEOVERSITTINGPANTSON[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINPANTSSITTING},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_TIMEOVERSITTINGPANTSON},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_TIMEOVER},
    {0, 0, 0}};

GameAction ACTIONS_TIMEOVERSITTINGPANTSOFF[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINTOILET},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_TIMEOVERSITTINGPANTSOFF},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_TIMEOVER},
    {0, 0, 0}};

GameAction ACTIONS_STARTINGGUN[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITPANTSSTANDING},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_STARTINGGUN},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_STARTINGGUN},
    {0, 0, 0}};

GameAction ACTIONS_SHITINPANTSWHILEOFF[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINPANTSWHILEOFF},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_SHITINPANTSWHILEOFF},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_FARTPANTSONSITTING[] = {
    {VERB_ONENTRY, ACTION_SCREENLINES, 92},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINPANTSSITTING},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_SHITINPANTSSITTING},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

// these should only trigger if not found in scene-specific actions
GameAction ACTIONS_GLOBAL[] = {
    {VERB_FARTLIGHTLY1, ACTION_TEXTOUTPUT, STRING_FARTEDLIGHTLY1},
    {VERB_FARTLIGHTLY1, ACTION_ADDTOTIMER, 60},
    {VERB_FARTLIGHTLY1, ACTION_FART, 1},
    {VERB_FARTLIGHTLY2, ACTION_TEXTOUTPUT, STRING_FARTEDLIGHTLY2},
    {VERB_FARTLIGHTLY2, ACTION_FART, 1},

    {VERB_TAKEPILLS, ACTION_TAKEPILLS, 45},
    {VERB_TAKEPILLS, ACTION_TEXTOUTPUT, STRING_EATPILLS},

    {VERB_TAKEPILLSTAKEN, ACTION_TEXTOUTPUT, STRING_ALREADYEATEN},

    {VERB_LOOKCLOTHES, ACTION_TEXTOUTPUT, STRING_LOOKCLOTHES},

    {VERB_LOOKPILLS, ACTION_TEXTOUTPUT, STRING_LOOKPILLS},

    {VERB_LOOKPILLSTAKEN, ACTION_TEXTOUTPUT, STRING_ALREADYEATEN},

    {VERB_LOOKPOCKET, ACTION_TEXTOUTPUT, STRING_LOOKPOCKETS},

    {VERB_LOOKPOCKETEMPTY, ACTION_TEXTOUTPUT, STRING_LOOKPOCKETSEMPTY},

    {VERB_LOOKSHOES, ACTION_TEXTOUTPUT, STRING_LOOKSHOES},
    {VERB_LOOKSHIRT, ACTION_TEXTOUTPUT, STRING_LOOKSHIRT},
    {VERB_LOOKHAIR, ACTION_TEXTOUTPUT, STRING_LOOKHAIR},

    {VERB_20SEC, ACTION_TEXTOUTPUT, STRING_TIMERUNNINGOUT},
    {VERB_5SEC, ACTION_TEXTOUTPUT, STRING_PEEKING},
};

GameState GameStates[] = {
    {0, 0},
    {STATE_MENU, ACTIONS_MENU},
    {STATE_STANDING, ACTIONS_STANDING},
    {STATE_STANDINGPANTSOFF, ACTIONS_STANDINGPANTSOFF},
    {STATE_DOOROPEN, ACTIONS_DOOROPEN},
    {STATE_DOOROPENPANTSOFF, ACTIONS_DOOROPENPANTSOFF},
    {STATE_ONTOILET, ACTIONS_ONTOILET},
    {STATE_ONTOILETPANTSOFF, ACTIONS_ONTOILETPANTSOFF},

    {STATE_AWARDS, ACTIONS_AWARDS},
    {STATE_CREDITS, NULL},

    // endings
    {STATE_SHITONFLOOR, ACTIONS_SHITONFLOOR},
    {STATE_SHITINTOILET, ACTIONS_SHITINTOILET},
    {STATE_SHITPANTSSTANDING, ACTIONS_SHITPANTSSTANDING},
    {STATE_SHITINPANTSSITTING, ACTIONS_SHITINPANTSSITTING},
    {STATE_DONTSHITPANTSON, ACTIONS_DONTSHITPANTSON},
    {STATE_BREAKPANTSON, ACTIONS_BREAKPANTSON},
    {STATE_FARTPANTSON, ACTIONS_FARTPANTSON},
    {STATE_FARTPANTSOFF, ACTIONS_FARTPANTSOFF},
    {STATE_DIEPANTSON, ACTIONS_DIEPANTSON},
    {STATE_DIEPANTSOFF, ACTIONS_DIEPANTSOFF},
    {STATE_DONTSHITPANTSOFF, ACTIONS_DONTSHITPANTSOFF},
    {STATE_BREAKPANTSOFF, ACTIONS_BREAKPANTSOFF},
    {STATE_PILLSSTANDINGPANTSON1, ACTIONS_PILLSSTANDINGPANTSON1},
    {STATE_PILLSSTANDINGPANTSON2, ACTIONS_PILLSSTANDINGPANTSON2},
    {STATE_PILLSSTANDINGPANTSON3, ACTIONS_PILLSSTANDINGPANTSON3},
    {STATE_STARTINGGUN, ACTIONS_STARTINGGUN},
    {STATE_PILLSSTANDINGPANTSOFF1, ACTIONS_PILLSSTANDINGPANTSOFF1},
    {STATE_PILLSSTANDINGPANTSOFF2, ACTIONS_PILLSSTANDINGPANTSOFF2},
    {STATE_PILLSSTANDINGPANTSOFF3, ACTIONS_PILLSSTANDINGPANTSOFF3},
    {STATE_PILLSSITTINGPANTSON1, ACTIONS_PILLSSITTINGPANTSON1},
    {STATE_PILLSSITTINGPANTSON2, ACTIONS_PILLSSITTINGPANTSON2},
    {STATE_PILLSSITTINGPANTSON3, ACTIONS_PILLSSITTINGPANTSON3},
    {STATE_PILLSSITTINGPANTSOFF1, ACTIONS_PILLSSITTINGPANTSOFF1},
    {STATE_PILLSSITTINGPANTSOFF2, ACTIONS_PILLSSITTINGPANTSOFF2},
    {STATE_PILLSSITTINGPANTSOFF3, ACTIONS_PILLSSITTINGPANTSOFF3},
    {STATE_TIMEOVERSTANDINGPANTSON, ACTIONS_TIMEOVERSTANDINGPANTSON},
    {STATE_TIMEOVERSITTINGPANTSON, ACTIONS_TIMEOVERSITTINGPANTSON},
    {STATE_TIMEOVERSTANDINGPANTSOFF, ACTIONS_TIMEOVERSTANDINGPANTSOFF},
    {STATE_TIMEOVERSITTINGPANTSOFF, ACTIONS_TIMEOVERSITTINGPANTSOFF},
    {STATE_SHITINPANTSWHILEOFF, ACTIONS_SHITINPANTSWHILEOFF},
    {STATE_FARTPANTSONSITTING, ACTIONS_FARTPANTSONSITTING},
    {STATE_DONTSHITPANTSONSITTING, ACTIONS_DONTSHITPANTSONSITTING},
    {STATE_DIEPANTSONSITTING, ACTIONS_DIEPANTSONSITTING},
    {STATE_DIEPANTSOFFSITTING, ACTIONS_DIEPANTSOFFSITTING},
    {STATE_DONTSHITPANTSOFFSITTING, ACTIONS_DONTSHITPANTSOFFSITTING},
};

char *FindString(int id)
{

    GameString *currstring = GameStrings;

    while (currstring != NULL)
    {

        if (currstring->ID == id)
        {
            return currstring->Text;
        }

        currstring = currstring->next;
    }

    return NULL;
}

int FindVerb(char *TextEntry)
{

    GameVerb *currverb = NULL;
    Synonym *currsyn = NULL;

    currverb = firstverb;
    while (currverb != NULL)
    {

        currsyn = currverb->Synonyms;
        while (currsyn != NULL)
        {

            if (strcmp(currsyn->Text, TextEntry) == 0)
                return currverb->ID;

            currsyn = currsyn->next;
        }

        currverb = currverb->next;
    }

    DisplayText("Can't find verb");
    return 0;
}

char filter[3] = {'\r', '\n', 0x00};

void LoadVerbs()
{

    char line[1024];

    int linenum = 1;

    GameString *currstring;
    GameString *prevstring = NULL;

    Synonym *prevsyn = NULL, *currsyn = NULL;
    GameVerb *prevverb = NULL, *currverb = NULL;
    char *token;
    char *pnt;
    FILE *file = fopen("strings.txt", "r");

    while (fgets(line, 1024, file))
    {

        // one string per line
        currstring = malloc(sizeof(GameString));
        currstring->ID = linenum;
        currstring->next = NULL;

        currstring->Text = malloc(strlen(line) + 1);
        strcpy(currstring->Text, line);
        currstring->Text[strcspn(currstring->Text, filter)] = 0; // strip newline

        if (prevstring != NULL)
            prevstring->next = currstring;

        if (GameStrings == NULL)
            GameStrings = currstring;

        prevstring = currstring;
        linenum++;
    }

    fclose(file);

    file = fopen("verbs.txt", "r");

    linenum = 1;
    while (fgets(line, 1024, file))
    {
        // one verb per line
        currverb = malloc(sizeof(GameVerb));
        currverb->ID = linenum;
        currverb->Synonyms = NULL;
        currverb->next = NULL;

        if (firstverb == NULL)
            firstverb = currverb;

        if (prevverb != NULL)
            prevverb->next = currverb;

        // Get the first token
        token = strtok(line, ",");

        prevsyn = NULL;

        // Walk through other tokens
        while (token != NULL)
        {

            // alloc a synonym
            currsyn = malloc(sizeof(Synonym));
            currsyn->next = NULL;

            // if first one, link it into verb
            if (currverb->Synonyms == NULL)
                currverb->Synonyms = currsyn;

            currsyn->Text = malloc(strlen(token) + 1);

            strcpy(currsyn->Text, token);
            currsyn->Text[strcspn(currsyn->Text, filter)] = 0; // strip newline

            /*pnt = currsyn->Text;
            while (*pnt != 0){
                printf("%02X", *pnt);
                pnt++;
            }

            printf(" -- %s\n", token);*/

            if (prevsyn != NULL)
                prevsyn->next = currsyn;

            prevsyn = currsyn;

            token = strtok(NULL, ","); // Subsequent calls
        }

        prevverb = currverb;

        linenum++;
    }

    fclose(file);

    /*currverb = firstverb;
    while (currverb != NULL) {

        printf("%d\n", currverb->ID);
        currsyn = currverb->Synonyms;
        while (currsyn != NULL){
            pnt = currsyn->Text;
            while (*pnt != 0){
                printf("%02X", *pnt);
                pnt++;
            }
            printf(" --- %s\n", currsyn->Text);
            currsyn = currsyn->next;
        }

        currverb = currverb->next;
    }*/
}

GameState *CurrState = &GameStates[1];

void EnterState()
{
    GameAction *StateEntryAction = CurrState->Actions;

    while (StateEntryAction->Verb != 0)
    {
        if (StateEntryAction->Verb == VERB_ONENTRY)
        {
            if (RunAction(StateEntryAction))
                break; // some actions abort future ones
        }
        StateEntryAction++;
    }
}

unsigned int OldAwards = 0;


void DrawAward(int x, int y, int Award, int NameString, int DescString) {

    DrawTextColor(x + 2, y, 0x0f, FindString(NameString));

    if (Awards & Award) { 
        DrawTextColor(x, y, 0x0c, "\xfb");
        DrawTextColor(x + 3, y + 1, 0x0e, FindString(DescString));
    }
    else {
        DrawTextColor(x + 3, y + 1, 0x0e, "??????");
    }
}

// returns 1 if action should stop future actions from running all others

int RunAction(GameAction *curraction)
{

    switch (curraction->Type)
    {
    case ACTION_TEXTOUTPUT:
        // printf("printf string %d\n", curraction->Action);
        // printf("%s\n", FindString(curraction->Action));
        DisplayText(FindString(curraction->Action));
        break;
    case ACTION_SCREENLINES:
        SetRows(curraction->Action);
        break;
    case ACTION_SETTEXTLINE:
        SetTextLine(curraction->Action);
        break;
    case ACTION_DISPLAYGFX:
        // printf("display gfx %d\n", curraction->Action);
        DisplayGFX(curraction->Action);
        break;

    case ACTION_GIVEAWARD:
        Awards |= curraction->Action;
        break;

    case ACTION_DISPLAYNEWAWARDS:
        if (Awards != OldAwards){
            CurrState = &GameStates[STATE_AWARDS];
            OldAwards = Awards;
            return 1;
        }
            
        break;

    case ACTION_TAKEPILLS:
        // printf("display gfx %d\n", curraction->Action);
        pillstaken = curraction->Action;
        if (pillstaken)
        {
            PillCountdown = 45;
        }
        break;

    // If action is 0, set to 0
    // otherwise increment fart counter
    case ACTION_FART:
        if (curraction->Action)
            FartCount ++;
        else 
            FartCount = 0;
        break;

    case ACTION_ADDTOTIMER:
        if (curraction->Action == 0)
        {
            Countdown = 40;
        }
        else
        {
            Countdown += curraction->Action;
        }
        break;

    case ACTION_GOTOSTATE:
        // printf("goto state %d\n", curraction->Action);
        CurrState = &GameStates[curraction->Action];
        break;

    case ACTION_DRAWMENU:
        switch (curraction->Action)
        {
            case 0:
                DrawTextColor(55, 21, 0x09, "A survival horror game");
                DrawTextColor(2, 23, 0x0f, "Instructions :");
                DrawTextColor(2, 24, 0x0f, "- To start type \"play\"");
                DrawTextColor(2, 25, 0x0f, "- To view achievements type \"awards\"");
                DrawTextColor(2, 27, 0x0f, "Goal :");
                DrawTextColor(2, 28, 0x0f, "- Don't shit your pants");
                DrawTextColor(2, 30, 0x0f, "- Type \"delete\" to delete your file");
                break;

            case 1:

                DrawAward(0, 14, AWARD_SHITINTOILET, STRING_AWARD1NAME, STRING_AWARD1DESC);
                DrawAward(0, 17, AWARD_SHITONFLOOR, STRING_AWARD2NAME, STRING_AWARD2DESC);
                DrawAward(0, 21, AWARD_SHITINPANTSSTANDING, STRING_AWARD3NAME, STRING_AWARD3DESC);
                DrawAward(0, 25, AWARD_SHITINPANTSSITTING, STRING_AWARD4NAME, STRING_AWARD4DESC);
                DrawAward(0, 29, AWARD_DIE, STRING_AWARD5NAME, STRING_AWARD5DESC);
                DrawAward(40, 17, AWARD_PILLSKICKIN, STRING_AWARD6NAME, STRING_AWARD6DESC);
                DrawAward(40, 21, AWARD_PILLSFAIL, STRING_AWARD7NAME, STRING_AWARD7DESC);
                DrawAward(40, 25, AWARD_STARTINGGUN, STRING_AWARD8NAME, STRING_AWARD8DESC);
                DrawAward(40, 29, AWARD_TIMEOVER, STRING_AWARD9NAME, STRING_AWARD9DESC);
                DrawAward(0, 32, AWARD_SHITKING, STRING_AWARD10NAME, STRING_AWARD10DESC);

            break;
        }

        break;
    }
    return 0;
}

void RunVerb(int Verb)
{
    GameAction *curraction = CurrState->Actions;
    char foundone = 0;

    int oldgamestate = CurrState->ID;

    while (curraction->Verb != 0)
    {

        // different string after you take pills
        if (pillstaken) {
            if (Verb == VERB_TAKEPILLS)
                Verb = VERB_TAKEPILLSTAKEN;
            if (Verb == VERB_LOOKPILLS)
                Verb = VERB_LOOKPILLSTAKEN;
            if (Verb == VERB_LOOKPOCKET)
                Verb = VERB_LOOKPOCKETEMPTY;

        }

        // fart lightly has a use count
        if (Verb == VERB_FARTLIGHTLY1) {
            Verb += FartCount;
        }

        if (curraction->Verb == VERB_WILDCARD || curraction->Verb == Verb)
        {
            foundone = 1;
            if (RunAction(curraction)){

                break; // some actions abort future ones
            }
            
        }

        curraction++;
    }

    // if we changed state, run the state's entry actions
    // keep doing so until state stabilizes
    while (CurrState->ID != oldgamestate){
        oldgamestate = CurrState->ID;
        EnterState();
    }

    if (foundone)
        return;

    // check global actions if we didn't find an override
    curraction = ACTIONS_GLOBAL;
    while (curraction->Verb != 0)
    {

        if (curraction->Verb == VERB_WILDCARD || curraction->Verb == Verb)
        {
            RunAction(curraction);
        }

        curraction++;
    }
}

void Gamelogic_Init()
{
    LoadVerbs();
}

void GameLogic_TextInput(char *Text)
{
    RunVerb(FindVerb(Text));
}

void Gamelogic_SecondTick()
{
    // don't tick outside main 6 states
    if (CurrState->ID < STATE_STANDING || CurrState->ID > STATE_ONTOILETPANTSOFF)
        return;

    Countdown--;

    if (Countdown == 20){
        RunVerb(VERB_20SEC);
    }

    else if (Countdown == 5){
        RunVerb(VERB_5SEC);
    }

    else if (!Countdown)
    {
        RunVerb(VERB_TIMEOUT);
    }

    if (PillCountdown)
    {

        PillCountdown--;

        if (!PillCountdown)
        {
            RunVerb(VERB_PILLSACTIVE);
        }
    }
}

/*int main(void)
{
    char inbuf[100];


    while(1) {
        fgets(inbuf, 100, stdin);
        inbuf[strcspn(inbuf, "\r\n")] = 0; // strip newline
        printf("inputted %s\n", inbuf);
        //printf("verb ID %d\n",FindVerb(inbuf));
        RunVerb(FindVerb(inbuf));
    }

    return 0;
}*/