

/* CGA ports */
#define CGA_CRTC_INDEX  0x3D4
#define CGA_CRTC_DATA   0x3D5
#define CGA_STATUS      0x3DA

#define CGA_MODE_CTRL   0x3D8

// linked list of synonyms
typedef struct _Synonym {

    char *Text;

    struct _Synonym *next;

} Synonym;

typedef struct _GameVerb {

    int ID;

    // Linked list, or array or something, of synonyms for this verb
    Synonym *Synonyms;

    // next in list
    struct _GameVerb *next;

} GameVerb;


typedef struct _GameString {

    int ID;

    char *Text;

    struct _GameString *next;

} GameString;

// An action that gets taken
typedef struct _gameaction {

    // Verb number
    int Verb;

    // Action Type, ACTION_x
    int Type;

    // index of either a string for TEXTOUTPUT or a state for GOTOSTATE
    unsigned long Action;

} GameAction;


// One state in the state machine
typedef struct _GameState {

    int ID;

    // array of actions one can take
    GameAction *Actions;

} GameState;

typedef struct _Graphic {

    long Length;

    // to set raster split
    unsigned int Lines;

    // pointer to le data
    char *Data;

} Graphic;

typedef struct _Note {

    unsigned int Time; // in ms from start

    unsigned char NoteNum;

} Note;


void DisplayGFX(int id);
void Decode(char *gfx, int length);
void DrawTextColor(unsigned int x, unsigned int y, unsigned char color, unsigned char *data);
void SetGFXLines(int rows);
void ClearScreen();
void DisplayText(char *text);
void SetTextLines(int lines, char HideTextInput);
void GFX_Init();
void GFX_DrawScreenSplit();
void ClearLine(int line);
void DrawChar(unsigned int x, unsigned int y, unsigned char data);
void GFX_DrawSprite(int id, int x, int y);
void GFX_Exit();
void SetTextWindowLine(int line);
void get_cursor_pos(int *row, int *col);

void Gamelogic_Init();
void Gamelogic_SecondTick();
void GameLogic_TextInput(char *Text);
int RunAction(GameAction *curraction);
void EnterState();

void PlaySound(Note *Song);
void Music_Task();

void Frontend_Exit();

extern unsigned int SplitAtLine;
extern Note SONG_INTRO[];
extern unsigned long NoteTable[];
extern GameState GameStates[];
extern int Countdown;
extern Note *JukeBox[];
extern GameAction ACTIONS_GLOBAL[];
extern unsigned int TextLine;
extern int CrownX, CrownY;
extern unsigned char GFXLine;

extern GameState *CurrState;

#define KEYBUF_SIZE 32
extern volatile unsigned char keybuf[KEYBUF_SIZE];
extern volatile unsigned int  keybuf_head;
extern volatile unsigned char last_keybyte;

unsigned long Awards;

#define rasterDisable() outp(CGA_MODE_CTRL, 0x01)
#define rasterEnable()  outp(CGA_MODE_CTRL, 0x09)

#define ACTION_NONE 0
#define ACTION_TEXTOUTPUT 1
#define ACTION_GOTOSTATE 2
#define ACTION_DELETEAWARDS 3
#define ACTION_EXITGAME 4
#define ACTION_ADDTOTIMER 5
#define ACTION_TAKEPILLS 6
#define ACTION_PLAYSOUND 7
#define ACTION_DISPLAYGFX 8
#define ACTION_GFXLINES 9
#define ACTION_DRAWMENU 10
#define ACTION_TEXTLINES 11
#define ACTION_FART 12
#define ACTION_GIVEAWARD 13
#define ACTION_DISPLAYNEWAWARDS 14
#define ACTION_CLEARSCREEN 15
#define ACTION_CROWNX 16
#define ACTION_CROWNY 17
#define ACTION_TEXTWINDOWLINE 18
#define ACTION_LOGENDING 19

#define SOUND_INTRO 0
#define SOUND_SUCCESS 1
#define SOUND_FAILURE 2
#define SOUND_AWARD 3
#define SOUND_ELVIS 4

#define VERB_PLAY 1
#define VERB_DELETE 2
#define VERB_AWARDS 3
#define VERB_MENU 4
#define VERB_QUIT 5
#define VERB_IDIOT 6
#define VERB_CREDITS 7
#define VERB_SHIT 8
#define VERB_SHITPANTS 9
#define VERB_SHITONFLOOR 10
#define VERB_FART 11
#define VERB_SHITTOILET 12
#define VERB_FARTLIGHTLY1 13
#define VERB_FARTLIGHTLY2 14
#define VERB_FARTLIGHTLY3 15
#define VERB_DONTSHIT 16
#define VERB_BREAK 17
#define VERB_DIE 18
#define VERB_REMOVEPANTS 19
#define VERB_WEARPANTS 20
#define VERB_OPENDOOR 21
#define VERB_PULLDOOR 22
#define VERB_CLOSEDOOR 23
#define VERB_SITTOILET 24
#define VERB_STAND 25
#define VERB_LOOK 26
#define VERB_LOOKWASHROOM 27
#define VERB_LOOKDOOR 28
#define VERB_LOOKTOILET 29
#define VERB_LOOKPOCKET 30
#define VERB_LOOKSHIRT 31
#define VERB_LOOKCLOTHES 32
#define VERB_LOOKPILLS 33
#define VERB_TAKEPILLS 34
#define VERB_LOOKHAIR 35
#define VERB_LOOKSHOES 36
#define VERB_LOOKPOCKETEMPTY 37
#define VERB_LOOKPILLSTAKEN 38
#define VERB_TAKEPILLSTAKEN 39
#define VERB_UNK 60
#define VERB_TIMEOUT 100
#define VERB_PILLSACTIVE 101
#define VERB_ONENTRY 102
#define VERB_WILDCARD 103
#define VERB_20SEC 104
#define VERB_5SEC 105


#define STRING_STARTSPACE 1
#define STRING_ENDSPACE 2
#define STRING_REMOVEPANTS 3
#define STRING_ALREADYOFF 4
#define STRING_GETOFFTOILET 5
#define STRING_WEARPANTS 6
#define STRING_ALREADYON 7
#define STRING_ALREADYOPEN 8
#define STRING_ALREADYMENU 9
#define STRING_IDIOT 10
#define STRING_WHATTOILET 11
#define STRING_FARTEDLIGHTLY1 12
#define STRING_FARTEDLIGHTLY2 13
#define STRING_CONCENTRATE 14
#define STRING_DONTKNOW 15
#define STRING_PUSHDOOR 16
#define STRING_PULLDOOR 17
#define STRING_ALREADYCLOSED 18
#define STRING_CANTREACH 19
#define STRING_CLOSEDOOR 20
#define STRING_SITONTOILET 21
#define STRING_STAND 22
#define STRING_STANDMORE 23
#define STRING_CANTSIT 24
#define STRING_ALREADYSITTING 25
#define STRING_LOOK 26
#define STRING_LOOKDOOROPEN 27
#define STRING_LOOKWASHROOM 28
#define STRING_LOOKDOOR 29
#define STRING_LOOKTOILET 30
#define STRING_CANTSEE 31
#define STRING_LOOKPOCKETS 32
#define STRING_LOOKPOCKETSEMPTY 33
#define STRING_LOOKSHIRT 34
#define STRING_LOOKCLOTHES 35
#define STRING_LOOKPILLS 36
#define STRING_ALREADYEATEN 37
#define STRING_EATPILLS 38
#define STRING_LOOKHAIR 39
#define STRING_LOOKSHOES 40
#define STRING_REALLYNEEDSHIT 41
#define STRING_TIMERUNNINGOUT 42
#define STRING_PEEKING 43
#define STRING_ENDING_SHITONFLOOR 44
#define STRING_ENDING_SHITINTOILET 45
#define STRING_ENDING_SHITPANTSSTANDING 46
#define STRING_ENDING_SHITINPANTSSITTING 47
#define STRING_ENDING_DONTSHITPANTSON 48
#define STRING_ENDING_BREAKPANTSON 49
#define STRING_ENDING_FARTPANTSON 50
#define STRING_ENDING_FARTPANTSOFF 51
#define STRING_ENDING_DIEPANTSON 52
#define STRING_ENDING_DIEPANTSOFF 53
#define STRING_ENDING_DONTSHITPANTSOFF 54
#define STRING_ENDING_BREAKPANTSOFF 55
#define STRING_ENDING_PILLSSTANDINGPANTSON1 56
#define STRING_ENDING_PILLSSTANDINGPANTSON2 57
#define STRING_ENDING_PILLSSTANDINGPANTSON3 58
#define STRING_ENDING_NULL 59
#define STRING_ENDING_STARTINGGUN 60
#define STRING_ENDING_PILLSSTANDINGPANTSOFF1 61
#define STRING_ENDING_PILLSSTANDINGPANTSOFF2 62
#define STRING_ENDING_PILLSSTANDINGPANTSOFF3 63
#define STRING_ENDING_PILLSSITTINGPANTSON1 64
#define STRING_ENDING_PILLSSITTINGPANTSON2 65
#define STRING_ENDING_PILLSSITTINGPANTSON3 66
#define STRING_ENDING_PILLSSITTINGPANTSOFF1 67
#define STRING_ENDING_PILLSSITTINGPANTSOFF2 68
#define STRING_ENDING_PILLSSITTINGPANTSOFF3 69
#define STRING_ENDING_TIMEOVERSTANDINGPANTSON 70
#define STRING_ENDING_TIMEOVERSITTINGPANTSON 71
#define STRING_ENDING_TIMEOVERSTANDINGPANTSOFF 72
#define STRING_ENDING_TIMEOVERSITTINGPANTSOFF 73
#define STRING_ENDING_SHITINPANTSWHILEOFF 74
#define STRING_ENDING_FARTPANTSONSITTING 75
#define STRING_ENDING_DONTSHITPANTSONSITTING 76
#define STRING_ENDING_DIEPANTSONSITTING 77
#define STRING_ENDING_DIEPANTSOFFSITTING 78
#define STRING_ENDING_DONTSHITPANTSOFFSITTING 79
#define STRING_LOOKNOPANTS 80
#define STRING_LOOKNOPANTSDOOROPEN 81
#define STRING_AWARD1NAME 82
#define STRING_AWARD1DESC 83
#define STRING_AWARD2NAME 84
#define STRING_AWARD2DESC 85
#define STRING_AWARD3NAME 86
#define STRING_AWARD3DESC 87
#define STRING_AWARD4NAME 88
#define STRING_AWARD4DESC 89
#define STRING_AWARD5NAME 90
#define STRING_AWARD5DESC 91
#define STRING_AWARD6NAME 92
#define STRING_AWARD6DESC 93
#define STRING_AWARD7NAME 94
#define STRING_AWARD7DESC 95
#define STRING_AWARD8NAME 96
#define STRING_AWARD8DESC 97
#define STRING_AWARD9NAME 98
#define STRING_AWARD9DESC 99
#define STRING_AWARD10NAME 100
#define STRING_AWARD10DESC 101
#define STRING_AWARD11NAME 102
#define STRING_AWARD11DESC 103
#define STRING_AWARD12NAME 104
#define STRING_AWARD12DESC 105
#define STRING_AWARD13NAME 106
#define STRING_AWARD13DESC 107
#define STRING_AWARD14NAME 108
#define STRING_AWARD14DESC 109
#define STRING_AWARD15NAME 110
#define STRING_AWARD15DESC 111
#define STRING_AWARD16NAME 112
#define STRING_AWARD16DESC 113
#define STRING_AWARD17NAME 114
#define STRING_AWARD17DESC 115
#define STRING_AWARD18NAME 116
#define STRING_AWARD18DESC 117
#define STRING_AWARD19NAME 118
#define STRING_AWARD19DESC 119
#define STRING_AWARD20NAME 120
#define STRING_AWARD20DESC 121
#define STRING_ENDING_SHITONBATHROOMFLOOR 122
#define STRING_ELVIS 123
#define STRING_UNK1 124
#define STRING_UNK2 125
#define STRING_END 126

#define STATE_MENU 1
#define STATE_STANDING 2
#define STATE_STANDINGPANTSOFF 3
#define STATE_DOOROPEN 4
#define STATE_DOOROPENPANTSOFF 5
#define STATE_ONTOILET 6
#define STATE_ONTOILETPANTSOFF 7
#define STATE_AWARDS 8
#define STATE_CREDITS 9
#define STATE_SHITONFLOOR 10
#define STATE_SHITINTOILET 11
#define STATE_SHITPANTSSTANDING 12
#define STATE_SHITINPANTSSITTING 13
#define STATE_DONTSHITPANTSON 14
#define STATE_BREAKPANTSON 15
#define STATE_FARTPANTSON 16
#define STATE_FARTPANTSOFF 17
#define STATE_DIEPANTSON 18
#define STATE_DIEPANTSOFF 19
#define STATE_DONTSHITPANTSOFF 20
#define STATE_BREAKPANTSOFF 21
#define STATE_PILLSSTANDINGPANTSON1 22
#define STATE_PILLSSTANDINGPANTSON2 23
#define STATE_PILLSSTANDINGPANTSON3 24
#define STATE_STARTINGGUN 25
#define STATE_PILLSSTANDINGPANTSOFF1 26
#define STATE_PILLSSTANDINGPANTSOFF2 27
#define STATE_PILLSSTANDINGPANTSOFF3 28
#define STATE_PILLSSITTINGPANTSON1 29
#define STATE_PILLSSITTINGPANTSON2 30
#define STATE_PILLSSITTINGPANTSON3 31
#define STATE_PILLSSITTINGPANTSOFF1 32
#define STATE_PILLSSITTINGPANTSOFF2 33
#define STATE_PILLSSITTINGPANTSOFF3 34
#define STATE_TIMEOVERSTANDINGPANTSON 35
#define STATE_TIMEOVERSITTINGPANTSON 36
#define STATE_TIMEOVERSTANDINGPANTSOFF 37
#define STATE_TIMEOVERSITTINGPANTSOFF 38
#define STATE_SHITINPANTSWHILEOFF 39
#define STATE_FARTPANTSONSITTING 40
#define STATE_DONTSHITPANTSONSITTING 41
#define STATE_DIEPANTSONSITTING 42
#define STATE_DIEPANTSOFFSITTING 43
#define STATE_DONTSHITPANTSOFFSITTING 44
#define STATE_SHITONBATHROOMFLOOR 45
#define STATE_AWARDS2 46
#define STATE_ELVIS 47
#define STATE_UNK1 48
#define STATE_UNK2 49
#define STATE_UNK3 50
#define STATE_END 51
#define STATECOUNT 52

#define GFX_MENU 1
#define GFX_STANDING 2
#define GFX_STANDINGPANTSOFF 3
#define GFX_DOOROPEN 4
#define GFX_DOOROPENPANTSOFF 5
#define GFX_ONTOILET 6
#define GFX_ONTOILETPANTSOFF 7
#define GFX_AWARDS 8
#define GFX_CREDITS 9
#define GFX_SHITONFLOOR 10
#define GFX_SHITINTOILET 11
#define GFX_SHITPANTSSTANDING 12
#define GFX_SHITINPANTSSITTING 13
/*#define GFX_DONTSHITPANTSON 14
#define GFX_BREAKPANTSON 15
#define GFX_FARTPANTSON 16
#define GFX_FARTPANTSOFF 17*/
#define GFX_DIEPANTSON 18
#define GFX_DIEPANTSOFF 19
//#define GFX_DONTSHITPANTSOFF 20
//#define GFX_BREAKPANTSOFF 21
#define GFX_PILLSSTANDINGPANTSON1 22
#define GFX_PILLSSTANDINGPANTSON2 23
//#define GFX_PILLSSTANDINGPANTSON3 24
#define GFX_STARTINGGUN 25
#define GFX_PILLSSTANDINGPANTSOFF1 26
#define GFX_PILLSSTANDINGPANTSOFF2 27
//#define GFX_PILLSSTANDINGPANTSOFF3 28
#define GFX_PILLSSITTINGPANTSON1 29
#define GFX_PILLSSITTINGPANTSON2 30
#define GFX_PILLSSITTINGPANTSON3 31
//#define GFX_PILLSSITTINGPANTSOFF1 32
#define GFX_PILLSSITTINGPANTSOFF2 33
//#define GFX_PILLSSITTINGPANTSOFF3 34
//#define GFX_TIMEOVERSTANDINGPANTSON 35
//#define GFX_TIMEOVERSITTINGPANTSON 36
//#define GFX_TIMEOVERSTANDINGPANTSOFF 37
//#define GFX_TIMEOVERSITTINGPANTSOFF 38
#define GFX_SHITINPANTSWHILEOFF 39
//#define GFX_FARTPANTSONSITTING 40
//#define GFX_DONTSHITPANTSONSITTING 41
#define GFX_DIEPANTSONSITTING 42
#define GFX_DIEPANTSOFFSITTING 43
//#define GFX_DONTSHITPANTSOFFSITTING 44
#define GFX_SHITONBATHROOMFLOOR 45
#define GFX_ELVIS 46
#define GFX_CROWN 47
#define GFX_UNK1 48
#define GFX_UNK2 49
#define GFX_END 50
#define GFXCOUNT 51

#define AWARD_SHITINTOILET 1
#define AWARD_SHITONFLOOR 2
#define AWARD_SHITINPANTSSTANDING 4
#define AWARD_SHITINPANTSSITTING 8
#define AWARD_DIE 16
#define AWARD_PILLSKICKIN 32
#define AWARD_PILLSFAIL 64
#define AWARD_STARTINGGUN 128
#define AWARD_TIMEOVER 256
#define AWARD_SHITPANTSWHILEOFF 512
#define AWARD_DONTSHIT 1024
#define AWARD_BELTSUSPENDERS 2048
#define AWARD_FART 4096
#define AWARD_SHITONBATHROOMFLOOR 8192
#define AWARD_ELVIS 16384
#define AWARD_SHITKING 32768
#define AWARD_UNK 2147483648

#define ENDING_SHITONFLOOR 1
#define ENDING_SHITINTOILET 2
#define ENDING_SHITPANTSSTANDING 4
#define ENDING_SHITINPANTSSITTING 8
#define ENDING_DONTSHITPANTSON 16
#define ENDING_BREAKPANTSON 32
#define ENDING_FARTPANTSON 64
#define ENDING_FARTPANTSOFF 128
#define ENDING_DIEPANTSON 256
#define ENDING_DIEPANTSOFF 512
#define ENDING_DONTSHITPANTSOFF 1024
#define ENDING_BREAKPANTSOFF 2048
#define ENDING_PILLSSTANDINGPANTSON 4096
#define ENDING_STARTINGGUN 8192
#define ENDING_PILLSSTANDINGPANTSOFF 16384
#define ENDING_PILLSSITTINGPANTSON 32768
#define ENDING_PILLSSITTINGPANTSOFF 65536
#define ENDING_TIMEOVERSTANDINGPANTSON 131072
#define ENDING_TIMEOVERSITTINGPANTSON 262144
#define ENDING_TIMEOVERSTANDINGPANTSOFF 524288
#define ENDING_TIMEOVERSITTINGPANTSOFF 1048576
#define ENDING_SHITINPANTSWHILEOFF 2097152
#define ENDING_FARTPANTSONSITTING 4194304
#define ENDING_DONTSHITPANTSONSITTING 8388608
#define ENDING_DIEPANTSONSITTING 16777216
#define ENDING_DIEPANTSOFFSITTING 33554432
#define ENDING_DONTSHITPANTSOFFSITTING 67108864
#define ENDING_SHITONBATHROOMFLOOR 134217728
#define ENDING_ELVIS 268435456
#define ENDING_UNK 536870912
#define NUMENDINGS 30