#include <stdio.h>
#include <stdlib.h>
#include "gamelogic.h"

// Huge state table covering every situation in the game
// This was probably a bad idea in retrospect
// But at least it makes it easier to account for every possibility

GameAction ACTIONS_MENU[] = {

    {VERB_ONENTRY, ACTION_CLEARSCREEN, 0},

    {VERB_ONENTRY, ACTION_DISPLAYNEWAWARDS, 0},

    {VERB_ONENTRY, ACTION_GFXLINES, 20},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_MENU},
    {VERB_ONENTRY, ACTION_CROWNX, 23},
    {VERB_ONENTRY, ACTION_CROWNY, 1},
    {VERB_ONENTRY, ACTION_TEXTLINES, 3},
    {VERB_ONENTRY, ACTION_DRAWMENU, 0},

    {VERB_PLAY, ACTION_GOTOSTATE, STATE_STANDING},
    {VERB_PLAY, ACTION_GFXLINES, 88}, // so the below text output draws in the correct place
    {VERB_PLAY, ACTION_TEXTOUTPUT, STRING_REALLYNEEDSHIT},
    {VERB_PLAY, ACTION_FART, 0},
    {VERB_PLAY, ACTION_TAKEPILLS, 0},
    {VERB_PLAY, ACTION_ADDTOTIMER, 0},

    {VERB_DELETE, ACTION_DELETEAWARDS, 0},
    {VERB_DELETE, ACTION_GOTOSTATE, STATE_AWARDS},

    {VERB_AWARDS, ACTION_GOTOSTATE, STATE_AWARDS},
    
    {VERB_MENU, ACTION_TEXTOUTPUT, STRING_ALREADYMENU},
    {VERB_QUIT, ACTION_EXITGAME, 0},
    {VERB_IDIOT, ACTION_TEXTOUTPUT, STRING_IDIOT},
    {VERB_CREDITS, ACTION_GOTOSTATE, STATE_CREDITS},
    {VERB_SHIT, ACTION_GOTOSTATE, STATE_STARTINGGUN},
    {0, 0, 0}
};

GameAction ACTIONS_AWARDS[] = {
    {VERB_ONENTRY, ACTION_CLEARSCREEN, 0},
    {VERB_ONENTRY, ACTION_GFXLINES, 14},
    {VERB_ONENTRY, ACTION_TEXTLINES, 3},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_AWARDS},
    {VERB_ONENTRY, ACTION_DRAWMENU, 1},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_AWARDS2},
    {0, 0, 0}
};

GameAction ACTIONS_AWARDS2[] = {
    {VERB_ONENTRY, ACTION_CLEARSCREEN, 0},
    {VERB_ONENTRY, ACTION_GFXLINES, 14},
    {VERB_ONENTRY, ACTION_TEXTLINES, 3},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_AWARDS},
    {VERB_ONENTRY, ACTION_DRAWMENU, 2},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}
};

GameAction ACTIONS_CREDITS[] = {
    {VERB_ONENTRY, ACTION_CLEARSCREEN, 0},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_CREDITS},
    {VERB_ONENTRY, ACTION_DRAWMENU, 3},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}
};


// main game (6 states)
GameAction ACTIONS_STANDING[] = { 
    {VERB_ONENTRY, ACTION_GFXLINES, 88},
    {VERB_ONENTRY, ACTION_TEXTLINES, 3},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_STANDING},
    {VERB_ONENTRY, ACTION_CROWNX, 16},
    {VERB_ONENTRY, ACTION_CROWNY, -6},

    {VERB_SHIT, ACTION_GOTOSTATE, STATE_SHITPANTSSTANDING},
    {VERB_SHITPANTS, ACTION_GOTOSTATE, STATE_SHITPANTSSTANDING},
    {VERB_FART, ACTION_GOTOSTATE, STATE_FARTPANTSON},
    {VERB_FARTLIGHTLY3, ACTION_GIVEAWARD, AWARD_FART},
    {VERB_FARTLIGHTLY3, ACTION_GOTOSTATE, STATE_SHITPANTSSTANDING},
    {VERB_SHITTOILET, ACTION_TEXTOUTPUT, STRING_WHATTOILET},
    {VERB_DONTSHIT, ACTION_GOTOSTATE, STATE_DONTSHITPANTSON},
    {VERB_BREAK, ACTION_GOTOSTATE, STATE_BREAKPANTSON},
    {VERB_DIE, ACTION_GOTOSTATE, STATE_DIEPANTSON},

    {VERB_REMOVEPANTS, ACTION_GOTOSTATE, STATE_STANDINGPANTSOFF},
    {VERB_REMOVEPANTS, ACTION_TEXTOUTPUT, STRING_REMOVEPANTS},

    {VERB_WEARPANTS, ACTION_TEXTOUTPUT, STRING_ALREADYON},
    {VERB_OPENDOOR, ACTION_TEXTOUTPUT, STRING_PUSHDOOR},
    
    {VERB_PULLDOOR, ACTION_GOTOSTATE, STATE_DOOROPEN},
    {VERB_PULLDOOR, ACTION_TEXTOUTPUT, STRING_PULLDOOR},
    {VERB_CLOSEDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYCLOSED},
    {VERB_SITTOILET, ACTION_TEXTOUTPUT, STRING_CANTSIT},
    {VERB_STAND, ACTION_TEXTOUTPUT, STRING_STANDMORE},
    {VERB_LOOK, ACTION_TEXTOUTPUT, STRING_LOOK},
    {VERB_LOOKWASHROOM, ACTION_TEXTOUTPUT, STRING_CANTSEE},
    {VERB_LOOKDOOR, ACTION_TEXTOUTPUT, STRING_LOOKDOOR},
    {VERB_LOOKTOILET, ACTION_TEXTOUTPUT, STRING_WHATTOILET},
    {VERB_TIMEOUT, ACTION_GOTOSTATE, STATE_TIMEOVERSTANDINGPANTSON},
    {VERB_PILLSACTIVE, ACTION_GOTOSTATE, STATE_PILLSSTANDINGPANTSON1},

    {VERB_UNK, ACTION_GOTOSTATE, STATE_UNK1},
    {0, 0, 0}};

GameAction ACTIONS_STANDINGPANTSOFF[] = {
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_STANDINGPANTSOFF},
    {VERB_ONENTRY, ACTION_CROWNX, 16},
    {VERB_ONENTRY, ACTION_CROWNY, -6},

    {VERB_SHIT, ACTION_GOTOSTATE, STATE_SHITONFLOOR},
    {VERB_SHITONFLOOR, ACTION_GOTOSTATE, STATE_SHITONFLOOR},
    {VERB_SHITPANTS, ACTION_GOTOSTATE, STATE_SHITINPANTSWHILEOFF},
    {VERB_FART, ACTION_GOTOSTATE, STATE_FARTPANTSOFF},
    {VERB_FARTLIGHTLY3, ACTION_GIVEAWARD, AWARD_FART},
    {VERB_FARTLIGHTLY3, ACTION_GOTOSTATE, STATE_SHITONFLOOR},
    {VERB_SHITTOILET, ACTION_TEXTOUTPUT, STRING_WHATTOILET},
    {VERB_DONTSHIT, ACTION_GOTOSTATE, STATE_DONTSHITPANTSOFF},
    {VERB_BREAK, ACTION_GOTOSTATE, STATE_BREAKPANTSOFF},
    {VERB_DIE, ACTION_GOTOSTATE, STATE_DIEPANTSOFF},
    {VERB_REMOVEPANTS, ACTION_TEXTOUTPUT, STRING_ALREADYOFF},
    {VERB_WEARPANTS, ACTION_GOTOSTATE, STATE_STANDING},
    {VERB_WEARPANTS, ACTION_TEXTOUTPUT, STRING_WEARPANTS},
    {VERB_OPENDOOR, ACTION_TEXTOUTPUT, STRING_PUSHDOOR},
    {VERB_PULLDOOR, ACTION_GOTOSTATE, STATE_DOOROPENPANTSOFF},
    {VERB_PULLDOOR, ACTION_TEXTOUTPUT, STRING_PULLDOOR},
    {VERB_CLOSEDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYCLOSED},
    {VERB_SITTOILET, ACTION_TEXTOUTPUT, STRING_CANTSIT},
    {VERB_STAND, ACTION_TEXTOUTPUT, STRING_STANDMORE},
    {VERB_LOOK, ACTION_TEXTOUTPUT, STRING_LOOKNOPANTS},
    {VERB_LOOKWASHROOM, ACTION_TEXTOUTPUT, STRING_CANTSEE},
    {VERB_LOOKDOOR, ACTION_TEXTOUTPUT, STRING_LOOKDOOR},
    {VERB_LOOKTOILET, ACTION_TEXTOUTPUT, STRING_WHATTOILET},
    {VERB_TIMEOUT, ACTION_GOTOSTATE, STATE_TIMEOVERSTANDINGPANTSOFF},
    {VERB_PILLSACTIVE, ACTION_GOTOSTATE, STATE_PILLSSTANDINGPANTSOFF1},
    {0, 0, 0}};

GameAction ACTIONS_DOOROPEN[] = {
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_DOOROPEN},
    {VERB_ONENTRY, ACTION_CROWNX, 16},
    {VERB_ONENTRY, ACTION_CROWNY, -6},

    {VERB_SHIT, ACTION_GOTOSTATE, STATE_SHITPANTSSTANDING},
    {VERB_FARTLIGHTLY3, ACTION_GIVEAWARD, AWARD_FART},
    {VERB_FARTLIGHTLY3, ACTION_GOTOSTATE, STATE_SHITPANTSSTANDING},
    {VERB_SHITPANTS, ACTION_GOTOSTATE, STATE_SHITPANTSSTANDING},
    {VERB_FART, ACTION_GOTOSTATE, STATE_FARTPANTSON},
    {VERB_SHITTOILET, ACTION_GOTOSTATE, STATE_SHITINPANTSSITTING},
    {VERB_DONTSHIT, ACTION_GOTOSTATE, STATE_DONTSHITPANTSON},
    {VERB_BREAK, ACTION_GOTOSTATE, STATE_BREAKPANTSON},
    {VERB_DIE, ACTION_GOTOSTATE, STATE_DIEPANTSON},
    {VERB_REMOVEPANTS, ACTION_GOTOSTATE, STATE_DOOROPENPANTSOFF},
    {VERB_REMOVEPANTS, ACTION_TEXTOUTPUT, STRING_REMOVEPANTS},
    {VERB_WEARPANTS, ACTION_TEXTOUTPUT, STRING_ALREADYON},
    {VERB_OPENDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_PULLDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_CLOSEDOOR, ACTION_GOTOSTATE, STATE_STANDING},
    {VERB_CLOSEDOOR, ACTION_TEXTOUTPUT, STRING_CLOSEDOOR},
    {VERB_SITTOILET, ACTION_GOTOSTATE, STATE_ONTOILET},
    {VERB_SITTOILET, ACTION_TEXTOUTPUT, STRING_SITONTOILET},
    {VERB_STAND, ACTION_TEXTOUTPUT, STRING_STANDMORE},
    {VERB_LOOK, ACTION_TEXTOUTPUT, STRING_LOOKDOOROPEN},
    {VERB_LOOKWASHROOM, ACTION_TEXTOUTPUT, STRING_LOOKWASHROOM},
    {VERB_LOOKDOOR, ACTION_TEXTOUTPUT, STRING_LOOKDOOR},
    {VERB_LOOKTOILET, ACTION_TEXTOUTPUT, STRING_LOOKTOILET},
    {VERB_TIMEOUT, ACTION_GOTOSTATE, STATE_TIMEOVERSTANDINGPANTSON},
    {VERB_PILLSACTIVE, ACTION_GOTOSTATE, STATE_PILLSSTANDINGPANTSON1},
    {0, 0, 0}};

GameAction ACTIONS_DOOROPENPANTSOFF[] = {
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_DOOROPENPANTSOFF},
    {VERB_ONENTRY, ACTION_CROWNX, 16},
    {VERB_ONENTRY, ACTION_CROWNY, -6},

    {VERB_SHIT, ACTION_GOTOSTATE, STATE_SHITONFLOOR},
    {VERB_SHITONFLOOR, ACTION_GOTOSTATE, STATE_SHITONFLOOR},
    {VERB_FARTLIGHTLY3, ACTION_GIVEAWARD, AWARD_FART},
    {VERB_FARTLIGHTLY3, ACTION_GOTOSTATE, STATE_SHITONFLOOR},
    {VERB_SHITPANTS, ACTION_GOTOSTATE, STATE_SHITINPANTSWHILEOFF},
    {VERB_FART, ACTION_GOTOSTATE, STATE_FARTPANTSOFF},
    {VERB_SHITTOILET, ACTION_GOTOSTATE, STATE_SHITINTOILET},
    {VERB_DONTSHIT, ACTION_GOTOSTATE, STATE_DONTSHITPANTSOFF},
    {VERB_BREAK, ACTION_GOTOSTATE, STATE_BREAKPANTSOFF},
    {VERB_DIE, ACTION_GOTOSTATE, STATE_DIEPANTSOFF},
    {VERB_REMOVEPANTS, ACTION_TEXTOUTPUT, STRING_ALREADYOFF},
    {VERB_WEARPANTS, ACTION_GOTOSTATE, STATE_DOOROPEN},
    {VERB_WEARPANTS, ACTION_TEXTOUTPUT, STRING_WEARPANTS},
    {VERB_OPENDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_PULLDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_CLOSEDOOR, ACTION_GOTOSTATE, STATE_STANDINGPANTSOFF},
    {VERB_CLOSEDOOR, ACTION_TEXTOUTPUT, STRING_CLOSEDOOR},
    {VERB_SITTOILET, ACTION_GOTOSTATE, STATE_ONTOILETPANTSOFF},
    {VERB_SITTOILET, ACTION_TEXTOUTPUT, STRING_SITONTOILET},
    {VERB_STAND, ACTION_TEXTOUTPUT, STRING_STANDMORE},
    {VERB_LOOK, ACTION_TEXTOUTPUT, STRING_LOOKNOPANTSDOOROPEN},
    {VERB_LOOKWASHROOM, ACTION_TEXTOUTPUT, STRING_LOOKWASHROOM},
    {VERB_LOOKDOOR, ACTION_TEXTOUTPUT, STRING_LOOKDOOR},
    {VERB_LOOKTOILET, ACTION_TEXTOUTPUT, STRING_LOOKTOILET},
    {VERB_TIMEOUT, ACTION_GOTOSTATE, STATE_TIMEOVERSTANDINGPANTSOFF},
    {VERB_PILLSACTIVE, ACTION_GOTOSTATE, STATE_PILLSSTANDINGPANTSOFF1},
    {0, 0, 0}};

GameAction ACTIONS_ONTOILET[] = {
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_ONTOILET},
    {VERB_ONENTRY, ACTION_CROWNX, 46},
    {VERB_ONENTRY, ACTION_CROWNY, -3},

    {VERB_SHIT, ACTION_GOTOSTATE, STATE_SHITINPANTSSITTING},
    {VERB_FARTLIGHTLY3, ACTION_GIVEAWARD, AWARD_FART},
    {VERB_FARTLIGHTLY3, ACTION_GOTOSTATE, STATE_SHITINPANTSSITTING},
    {VERB_SHITPANTS, ACTION_GOTOSTATE, STATE_SHITINPANTSSITTING},
    {VERB_FART, ACTION_GOTOSTATE, STATE_FARTPANTSONSITTING},
    {VERB_SHITTOILET, ACTION_GOTOSTATE, STATE_SHITINPANTSSITTING},
    {VERB_DONTSHIT, ACTION_GOTOSTATE, STATE_DONTSHITPANTSONSITTING},
    {VERB_BREAK, ACTION_TEXTOUTPUT, STRING_CONCENTRATE},
    {VERB_DIE, ACTION_GOTOSTATE, STATE_DIEPANTSONSITTING},
    {VERB_REMOVEPANTS, ACTION_TEXTOUTPUT, STRING_GETOFFTOILET},
    {VERB_WEARPANTS, ACTION_TEXTOUTPUT, STRING_ALREADYON},
    {VERB_OPENDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_PULLDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_CLOSEDOOR, ACTION_TEXTOUTPUT, STRING_CANTREACH},
    {VERB_SITTOILET, ACTION_TEXTOUTPUT, STRING_ALREADYSITTING},
    {VERB_STAND, ACTION_GOTOSTATE, STATE_DOOROPEN},
    {VERB_STAND, ACTION_TEXTOUTPUT, STRING_STAND},
    {VERB_LOOK, ACTION_TEXTOUTPUT, STRING_LOOKDOOROPEN},
    {VERB_LOOKWASHROOM, ACTION_TEXTOUTPUT, STRING_LOOKWASHROOM},
    {VERB_LOOKDOOR, ACTION_TEXTOUTPUT, STRING_LOOKDOOR},
    {VERB_LOOKTOILET, ACTION_TEXTOUTPUT, STRING_LOOKTOILET},
    {VERB_TIMEOUT, ACTION_GOTOSTATE, STATE_TIMEOVERSITTINGPANTSON},
    {VERB_PILLSACTIVE, ACTION_GOTOSTATE, STATE_PILLSSITTINGPANTSON1},
    {0, 0, 0}};

GameAction ACTIONS_ONTOILETPANTSOFF[] = {
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_ONTOILETPANTSOFF},
    {VERB_ONENTRY, ACTION_CROWNX, 46},
    {VERB_ONENTRY, ACTION_CROWNY, -3},

    {VERB_SHIT, ACTION_GOTOSTATE, STATE_SHITINTOILET},
    {VERB_SHITONFLOOR, ACTION_GOTOSTATE, STATE_SHITONBATHROOMFLOOR},
    {VERB_FARTLIGHTLY3, ACTION_GIVEAWARD, AWARD_FART},
    {VERB_FARTLIGHTLY3, ACTION_GOTOSTATE, STATE_SHITINTOILET},
    {VERB_SHITPANTS, ACTION_GOTOSTATE, STATE_SHITINPANTSWHILEOFF},
    {VERB_FART, ACTION_GOTOSTATE, STATE_SHITINTOILET},
    {VERB_SHITTOILET, ACTION_GOTOSTATE, STATE_SHITINTOILET},
    {VERB_DONTSHIT, ACTION_GOTOSTATE, STATE_DONTSHITPANTSOFFSITTING},
    {VERB_BREAK, ACTION_TEXTOUTPUT, STRING_CONCENTRATE},
    {VERB_DIE, ACTION_GOTOSTATE, STATE_DIEPANTSOFFSITTING},
    {VERB_DIE, ACTION_GOTOSTATE, STATE_ELVIS},
    {VERB_REMOVEPANTS, ACTION_TEXTOUTPUT, STRING_ALREADYOFF},
    {VERB_WEARPANTS, ACTION_TEXTOUTPUT, STRING_GETOFFTOILET},
    {VERB_OPENDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_PULLDOOR, ACTION_TEXTOUTPUT, STRING_ALREADYOPEN},
    {VERB_CLOSEDOOR, ACTION_TEXTOUTPUT, STRING_CANTREACH},
    {VERB_SITTOILET, ACTION_TEXTOUTPUT, STRING_ALREADYSITTING},
    {VERB_STAND, ACTION_GOTOSTATE, STATE_DOOROPENPANTSOFF},
    {VERB_STAND, ACTION_TEXTOUTPUT, STRING_STAND},
    {VERB_LOOK, ACTION_TEXTOUTPUT, STRING_LOOKNOPANTSDOOROPEN},
    {VERB_LOOKWASHROOM, ACTION_TEXTOUTPUT, STRING_LOOKWASHROOM},
    {VERB_LOOKDOOR, ACTION_TEXTOUTPUT, STRING_LOOKDOOR},
    {VERB_LOOKTOILET, ACTION_TEXTOUTPUT, STRING_LOOKTOILET},
    {VERB_TIMEOUT, ACTION_GOTOSTATE, STATE_TIMEOVERSITTINGPANTSOFF},
    {VERB_PILLSACTIVE, ACTION_GOTOSTATE, STATE_PILLSSITTINGPANTSOFF1},
    {0, 0, 0}};


// endings
GameAction ACTIONS_SHITONFLOOR[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_SUCCESS},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, 67, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITONFLOOR},
    {VERB_ONENTRY, ACTION_CROWNX, 41},
    {VERB_ONENTRY, ACTION_CROWNY, -6},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_SHITONFLOOR},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_SHITONFLOOR},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_SHITONFLOOR},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_SHITINTOILET[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_SUCCESS},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINTOILET},
    {VERB_ONENTRY, ACTION_CROWNX, 31},
    {VERB_ONENTRY, ACTION_CROWNY, 0},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_SHITINTOILET},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_SHITINTOILET},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_SHITINTOILET},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_SHITPANTSSTANDING[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_FAILURE},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITPANTSSTANDING},
    {VERB_ONENTRY, ACTION_CROWNX, 34},
    {VERB_ONENTRY, ACTION_CROWNY, -6},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_SHITPANTSSTANDING},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_SHITINPANTSSTANDING},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_SHITPANTSSTANDING},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_SHITINPANTSSITTING[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_FAILURE},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINPANTSSITTING},
    {VERB_ONENTRY, ACTION_CROWNX, 31},
    {VERB_ONENTRY, ACTION_CROWNY, 10},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_SHITINPANTSSITTING},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_SHITINPANTSSITTING},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_SHITINPANTSSITTING},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_BREAKPANTSON[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_FAILURE},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITPANTSSTANDING},
    {VERB_ONENTRY, ACTION_CROWNX, 31},
    {VERB_ONENTRY, ACTION_CROWNY, 10},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_BREAKPANTSON},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_SHITINPANTSSTANDING},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_BREAKPANTSON},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}
};

GameAction ACTIONS_BREAKPANTSOFF[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_SUCCESS},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITONFLOOR},
    {VERB_ONENTRY, ACTION_CROWNX, 41},
    {VERB_ONENTRY, ACTION_CROWNY, -6},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_BREAKPANTSOFF},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_BREAKPANTSOFF},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_FARTPANTSON[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_FAILURE},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITPANTSSTANDING},
    {VERB_ONENTRY, ACTION_CROWNX, 34},
    {VERB_ONENTRY, ACTION_CROWNY, -6},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_FARTPANTSON},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_FARTPANTSON},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_FARTPANTSOFF[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_SUCCESS},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITONFLOOR},
    {VERB_ONENTRY, ACTION_CROWNX, 41},
    {VERB_ONENTRY, ACTION_CROWNY, -6},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_FARTPANTSOFF},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_FARTPANTSOFF},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_DIEPANTSON[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_FAILURE},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_DIEPANTSON},
    {VERB_ONENTRY, ACTION_CROWNX, 2},
    {VERB_ONENTRY, ACTION_CROWNY, 64},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_DIEPANTSON},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_DIE},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_DIEPANTSON},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_DIEPANTSOFF[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_SUCCESS},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_DIEPANTSOFF},
    {VERB_ONENTRY, ACTION_CROWNX, 2},
    {VERB_ONENTRY, ACTION_CROWNY, 64},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_DIEPANTSOFF},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_DIE},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_DIEPANTSOFF},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_DIEPANTSONSITTING[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_FAILURE},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_DIEPANTSONSITTING},
    {VERB_ONENTRY, ACTION_CROWNX, 31},
    {VERB_ONENTRY, ACTION_CROWNY, 10},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_DIEPANTSONSITTING},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_DIE},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_DIEPANTSONSITTING},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_DIEPANTSOFFSITTING[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_SUCCESS},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_DIEPANTSOFFSITTING},
    {VERB_ONENTRY, ACTION_CROWNX, 31},
    {VERB_ONENTRY, ACTION_CROWNY, 10},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_DIEPANTSOFFSITTING},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_DIE},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_DIEPANTSOFFSITTING},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_DONTSHITPANTSON[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_FAILURE},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITPANTSSTANDING},
    {VERB_ONENTRY, ACTION_CROWNX, 34},
    {VERB_ONENTRY, ACTION_CROWNY, -6},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_DONTSHITPANTSON},
    {VERB_ONENTRY, ACTION_GIVEAWARD, AWARD_DONTSHIT},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_DONTSHITPANTSON},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_DONTSHITPANTSOFF[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_SUCCESS},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITONFLOOR},
    {VERB_ONENTRY, ACTION_CROWNX, 41},
    {VERB_ONENTRY, ACTION_CROWNY, -6},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_DONTSHITPANTSOFF},
    {VERB_ONENTRY, ACTION_GIVEAWARD, AWARD_DONTSHIT},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_DONTSHITPANTSOFF},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_DONTSHITPANTSONSITTING[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_FAILURE},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINPANTSSITTING},
    {VERB_ONENTRY, ACTION_CROWNX, 31},
    {VERB_ONENTRY, ACTION_CROWNY, 10},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_DONTSHITPANTSONSITTING},
    {VERB_ONENTRY, ACTION_GIVEAWARD, AWARD_DONTSHIT},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_DONTSHITPANTSONSITTING},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_DONTSHITPANTSOFFSITTING[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_SUCCESS},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINTOILET},
    {VERB_ONENTRY, ACTION_CROWNX, 31},
    {VERB_ONENTRY, ACTION_CROWNY, 0},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_DONTSHITPANTSOFFSITTING},
    {VERB_ONENTRY, ACTION_GIVEAWARD, AWARD_DONTSHIT},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_DONTSHITPANTSOFFSITTING},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSTANDINGPANTSON1[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_SUCCESS},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_PILLSSTANDINGPANTSON1},
    {VERB_ONENTRY, ACTION_CROWNX, 34},
    {VERB_ONENTRY, ACTION_CROWNY, -6},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSTANDINGPANTSON1},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_PILLSSTANDINGPANTSON2},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSTANDINGPANTSON2[] = {
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_PILLSSTANDINGPANTSON2},
    {VERB_ONENTRY, ACTION_CROWNX, 34},
    {VERB_ONENTRY, ACTION_CROWNY, -6},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSTANDINGPANTSON2},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_PILLSSTANDINGPANTSON3},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSTANDINGPANTSON3[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_FAILURE},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITPANTSSTANDING},
    {VERB_ONENTRY, ACTION_CROWNX, 34},
    {VERB_ONENTRY, ACTION_CROWNY, -6},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSTANDINGPANTSON3},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_PILLSKICKIN},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_PILLSFAIL},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_PILLSSTANDINGPANTSON},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSTANDINGPANTSOFF1[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_SUCCESS},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_PILLSSTANDINGPANTSON1},
    {VERB_ONENTRY, ACTION_CROWNX, 34},
    {VERB_ONENTRY, ACTION_CROWNY, -6},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSTANDINGPANTSOFF1},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_PILLSSTANDINGPANTSOFF2},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSTANDINGPANTSOFF2[] = {
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_PILLSSTANDINGPANTSON2},
    {VERB_ONENTRY, ACTION_CROWNX, 34},
    {VERB_ONENTRY, ACTION_CROWNY, -6},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSTANDINGPANTSOFF2},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_PILLSSTANDINGPANTSOFF3},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSTANDINGPANTSOFF3[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_SUCCESS},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITONFLOOR},
    {VERB_ONENTRY, ACTION_CROWNX, 41},
    {VERB_ONENTRY, ACTION_CROWNY, -6},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSTANDINGPANTSOFF3},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_PILLSKICKIN},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_PILLSFAIL},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_PILLSSTANDINGPANTSOFF},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSITTINGPANTSON1[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_SUCCESS},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_PILLSSITTINGPANTSON1},
    {VERB_ONENTRY, ACTION_CROWNX, 31},
    {VERB_ONENTRY, ACTION_CROWNY, 0},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSITTINGPANTSON1},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_PILLSSITTINGPANTSON2},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSITTINGPANTSON2[] = {
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_PILLSSITTINGPANTSON2},
    {VERB_ONENTRY, ACTION_CROWNX, 31},
    {VERB_ONENTRY, ACTION_CROWNY, 0},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSITTINGPANTSON2},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_PILLSSITTINGPANTSON3},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSITTINGPANTSON3[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_FAILURE},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINPANTSSITTING},
    {VERB_ONENTRY, ACTION_CROWNX, 31},
    {VERB_ONENTRY, ACTION_CROWNY, 10},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSITTINGPANTSON3},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_PILLSKICKIN},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_PILLSFAIL},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_PILLSSITTINGPANTSON},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSITTINGPANTSOFF1[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_SUCCESS},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINTOILET},
    {VERB_ONENTRY, ACTION_CROWNX, 31},
    {VERB_ONENTRY, ACTION_CROWNY, 0},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSITTINGPANTSOFF1},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_PILLSSITTINGPANTSOFF2},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSITTINGPANTSOFF2[] = {
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_PILLSSITTINGPANTSOFF2},
    {VERB_ONENTRY, ACTION_CROWNX, 31},
    {VERB_ONENTRY, ACTION_CROWNY, 0},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSITTINGPANTSOFF2},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_PILLSSITTINGPANTSOFF3},
    {0, 0, 0}};

GameAction ACTIONS_PILLSSITTINGPANTSOFF3[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_SUCCESS},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINTOILET},
     {VERB_ONENTRY, ACTION_CROWNX, 31},
    {VERB_ONENTRY, ACTION_CROWNY, 0},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_PILLSSITTINGPANTSOFF3},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_PILLSKICKIN},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_PILLSFAIL},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_BELTSUSPENDERS},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_PILLSSITTINGPANTSOFF},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_TIMEOVERSTANDINGPANTSON[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_FAILURE},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITPANTSSTANDING},
    {VERB_ONENTRY, ACTION_CROWNX, 34},
    {VERB_ONENTRY, ACTION_CROWNY, -6},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_TIMEOVERSTANDINGPANTSON},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_TIMEOVERSTANDINGPANTSON},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_TIMEOVER},
    {0, 0, 0}};

GameAction ACTIONS_TIMEOVERSTANDINGPANTSOFF[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_SUCCESS},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITONFLOOR},
    {VERB_ONENTRY, ACTION_CROWNX, 41},
    {VERB_ONENTRY, ACTION_CROWNY, -6},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_TIMEOVERSTANDINGPANTSOFF},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_TIMEOVERSTANDINGPANTSOFF},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_TIMEOVER},
    {0, 0, 0}};

GameAction ACTIONS_TIMEOVERSITTINGPANTSON[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_FAILURE},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINPANTSSITTING},
    {VERB_ONENTRY, ACTION_CROWNX, 31},
    {VERB_ONENTRY, ACTION_CROWNY, 10},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_TIMEOVERSITTINGPANTSON},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_TIMEOVERSITTINGPANTSON},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_TIMEOVER},
    {0, 0, 0}};

GameAction ACTIONS_TIMEOVERSITTINGPANTSOFF[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_SUCCESS},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINTOILET},
    {VERB_ONENTRY, ACTION_CROWNX, 31},
    {VERB_ONENTRY, ACTION_CROWNY, 0},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_TIMEOVERSITTINGPANTSOFF},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_TIMEOVERSITTINGPANTSOFF},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_TIMEOVER},
    {0, 0, 0}};

GameAction ACTIONS_STARTINGGUN[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_FAILURE},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITPANTSSTANDING},
    {VERB_ONENTRY, ACTION_CROWNX, 34},
    {VERB_ONENTRY, ACTION_CROWNY, -6},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_STARTINGGUN},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_STARTINGGUN},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_STARTINGGUN},
    {0, 0, 0}};

GameAction ACTIONS_SHITINPANTSWHILEOFF[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_FAILURE},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINPANTSWHILEOFF},
    {VERB_ONENTRY, ACTION_CROWNX, 42},
    {VERB_ONENTRY, ACTION_CROWNY, 0},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_SHITINPANTSWHILEOFF},
    {VERB_ONENTRY, ACTION_GIVEAWARD, AWARD_SHITPANTSWHILEOFF},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_SHITINPANTSWHILEOFF},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_FARTPANTSONSITTING[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_FAILURE},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITINPANTSSITTING},
    {VERB_ONENTRY, ACTION_CROWNX, 31},
    {VERB_ONENTRY, ACTION_CROWNY, 10},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_SHITINPANTSSITTING},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_FARTPANTSONSITTING},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_SHITONBATHROOMFLOOR[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_SUCCESS},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_SHITONBATHROOMFLOOR},
    {VERB_ONENTRY, ACTION_CROWNX, 31},
    {VERB_ONENTRY, ACTION_CROWNY, 0},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ENDING_SHITONBATHROOMFLOOR},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_SHITONBATHROOMFLOOR},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_SHITONBATHROOMFLOOR},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}};

GameAction ACTIONS_ELVIS[] = {
    {VERB_ONENTRY, ACTION_PLAYSOUND, SOUND_ELVIS},
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_ELVIS},
    {VERB_ONENTRY, ACTION_CROWNX, 31},
    {VERB_ONENTRY, ACTION_CROWNY, 7},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_ELVIS},
    {VERB_WILDCARD, ACTION_GIVEAWARD, AWARD_ELVIS},
    {VERB_WILDCARD, ACTION_LOGENDING, ENDING_ELVIS},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}
};

GameAction ACTIONS_UNK1[] = {
    {VERB_ONENTRY, ACTION_GFXLINES, 92},
    {VERB_ONENTRY, ACTION_TEXTLINES, 2},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_UNK1},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_UNK1},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_UNK2},
    {0, 0, 0}
};

GameAction ACTIONS_UNK2[] = {
    {VERB_ONENTRY, ACTION_GFXLINES, 1},
    {VERB_ONENTRY, ACTION_TEXTLINES, 25},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_UNK2},
    {VERB_WILDCARD, ACTION_GOTOSTATE, STATE_MENU},
    {0, 0, 0}
};

GameAction ACTIONS_END[] = { 
    {VERB_ONENTRY, ACTION_GFXLINES, 88},
    {VERB_ONENTRY, ACTION_TEXTLINES, 3},
    {VERB_ONENTRY, ACTION_DISPLAYGFX, GFX_END},
    {VERB_ONENTRY, ACTION_TEXTOUTPUT, STRING_END},
    {0, 0, 0}
};


// these should only trigger if verb not found in scene-specific actions
GameAction ACTIONS_GLOBAL[] = {
    {VERB_FARTLIGHTLY1, ACTION_TEXTOUTPUT, STRING_FARTEDLIGHTLY1},
    {VERB_FARTLIGHTLY1, ACTION_ADDTOTIMER, 60},
    {VERB_FARTLIGHTLY1, ACTION_FART, 1},
    {VERB_FARTLIGHTLY2, ACTION_TEXTOUTPUT, STRING_FARTEDLIGHTLY2},
    {VERB_FARTLIGHTLY2, ACTION_FART, 1},

    {VERB_TAKEPILLS, ACTION_TAKEPILLS, 45},
    {VERB_TAKEPILLS, ACTION_TEXTOUTPUT, STRING_EATPILLS},

    {VERB_TAKEPILLSTAKEN, ACTION_TEXTOUTPUT, STRING_ALREADYEATEN},

    {VERB_LOOKCLOTHES, ACTION_TEXTOUTPUT, STRING_LOOKCLOTHES},

    {VERB_LOOKPILLS, ACTION_TEXTOUTPUT, STRING_LOOKPILLS},

    {VERB_LOOKPILLSTAKEN, ACTION_TEXTOUTPUT, STRING_ALREADYEATEN},

    {VERB_LOOKPOCKET, ACTION_TEXTOUTPUT, STRING_LOOKPOCKETS},

    {VERB_LOOKPOCKETEMPTY, ACTION_TEXTOUTPUT, STRING_LOOKPOCKETSEMPTY},

    {VERB_LOOKSHOES, ACTION_TEXTOUTPUT, STRING_LOOKSHOES},
    {VERB_LOOKSHIRT, ACTION_TEXTOUTPUT, STRING_LOOKSHIRT},
    {VERB_LOOKHAIR, ACTION_TEXTOUTPUT, STRING_LOOKHAIR},

    {VERB_20SEC, ACTION_TEXTOUTPUT, STRING_TIMERUNNINGOUT},
    {VERB_5SEC, ACTION_TEXTOUTPUT, STRING_PEEKING},
    {VERB_IDFA, ACTION_IDFA, 0},
    {VERB_IDKFA, ACTION_IDKFA, 0},
};


GameState GameStates[] = {
    {0, 0},
    {STATE_MENU, ACTIONS_MENU},
    {STATE_STANDING, ACTIONS_STANDING},
    {STATE_STANDINGPANTSOFF, ACTIONS_STANDINGPANTSOFF},
    {STATE_DOOROPEN, ACTIONS_DOOROPEN},
    {STATE_DOOROPENPANTSOFF, ACTIONS_DOOROPENPANTSOFF},
    {STATE_ONTOILET, ACTIONS_ONTOILET},
    {STATE_ONTOILETPANTSOFF, ACTIONS_ONTOILETPANTSOFF},

    {STATE_AWARDS, ACTIONS_AWARDS},
    {STATE_CREDITS, ACTIONS_CREDITS},

    // endings
    {STATE_SHITONFLOOR, ACTIONS_SHITONFLOOR},
    {STATE_SHITINTOILET, ACTIONS_SHITINTOILET},
    {STATE_SHITPANTSSTANDING, ACTIONS_SHITPANTSSTANDING},
    {STATE_SHITINPANTSSITTING, ACTIONS_SHITINPANTSSITTING},
    {STATE_DONTSHITPANTSON, ACTIONS_DONTSHITPANTSON},
    {STATE_BREAKPANTSON, ACTIONS_BREAKPANTSON},
    {STATE_FARTPANTSON, ACTIONS_FARTPANTSON},
    {STATE_FARTPANTSOFF, ACTIONS_FARTPANTSOFF},
    {STATE_DIEPANTSON, ACTIONS_DIEPANTSON},
    {STATE_DIEPANTSOFF, ACTIONS_DIEPANTSOFF},
    {STATE_DONTSHITPANTSOFF, ACTIONS_DONTSHITPANTSOFF},
    {STATE_BREAKPANTSOFF, ACTIONS_BREAKPANTSOFF},
    {STATE_PILLSSTANDINGPANTSON1, ACTIONS_PILLSSTANDINGPANTSON1},
    {STATE_PILLSSTANDINGPANTSON2, ACTIONS_PILLSSTANDINGPANTSON2},
    {STATE_PILLSSTANDINGPANTSON3, ACTIONS_PILLSSTANDINGPANTSON3},
    {STATE_STARTINGGUN, ACTIONS_STARTINGGUN},
    {STATE_PILLSSTANDINGPANTSOFF1, ACTIONS_PILLSSTANDINGPANTSOFF1},
    {STATE_PILLSSTANDINGPANTSOFF2, ACTIONS_PILLSSTANDINGPANTSOFF2},
    {STATE_PILLSSTANDINGPANTSOFF3, ACTIONS_PILLSSTANDINGPANTSOFF3},
    {STATE_PILLSSITTINGPANTSON1, ACTIONS_PILLSSITTINGPANTSON1},
    {STATE_PILLSSITTINGPANTSON2, ACTIONS_PILLSSITTINGPANTSON2},
    {STATE_PILLSSITTINGPANTSON3, ACTIONS_PILLSSITTINGPANTSON3},
    {STATE_PILLSSITTINGPANTSOFF1, ACTIONS_PILLSSITTINGPANTSOFF1},
    {STATE_PILLSSITTINGPANTSOFF2, ACTIONS_PILLSSITTINGPANTSOFF2},
    {STATE_PILLSSITTINGPANTSOFF3, ACTIONS_PILLSSITTINGPANTSOFF3},
    {STATE_TIMEOVERSTANDINGPANTSON, ACTIONS_TIMEOVERSTANDINGPANTSON},
    {STATE_TIMEOVERSITTINGPANTSON, ACTIONS_TIMEOVERSITTINGPANTSON},
    {STATE_TIMEOVERSTANDINGPANTSOFF, ACTIONS_TIMEOVERSTANDINGPANTSOFF},
    {STATE_TIMEOVERSITTINGPANTSOFF, ACTIONS_TIMEOVERSITTINGPANTSOFF},
    {STATE_SHITINPANTSWHILEOFF, ACTIONS_SHITINPANTSWHILEOFF},
    {STATE_FARTPANTSONSITTING, ACTIONS_FARTPANTSONSITTING},
    {STATE_DONTSHITPANTSONSITTING, ACTIONS_DONTSHITPANTSONSITTING},
    {STATE_DIEPANTSONSITTING, ACTIONS_DIEPANTSONSITTING},
    {STATE_DIEPANTSOFFSITTING, ACTIONS_DIEPANTSOFFSITTING},
    {STATE_DONTSHITPANTSOFFSITTING, ACTIONS_DONTSHITPANTSOFFSITTING},
    {STATE_SHITONBATHROOMFLOOR, ACTIONS_SHITONBATHROOMFLOOR},
    {STATE_AWARDS2, ACTIONS_AWARDS2},
    {STATE_ELVIS, ACTIONS_ELVIS},
    {STATE_UNK1, ACTIONS_UNK1},
    {STATE_UNK2, ACTIONS_UNK2},
    {STATE_UNK3, NULL},
    {STATE_END, ACTIONS_END},
}; 